#!/usr/bin/env node
// Detect and summarise a repository's diagrams-as-code corpus, and say which of it is
// stale. Absence is normal and not an error: with no corpus the script prints one line
// and exits 0, so an explainer run can always call it. See references/diagram-corpus.md.
//
//   diagram-corpus.mjs --repo DIR [--dir REL] [--json] [--stale-only] [--limit N]
//
// --dir names the corpus root relative to the repo; without it these are tried in order:
//   docs/diagrams, docs/diagram, docs/architecture/diagrams, docs/design/diagrams, diagrams
//
// Exit codes: 0 always, unless --repo is missing or unreadable (2).
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, resolve, extname, sep } from 'node:path';
import { execFileSync } from 'node:child_process';

const CANDIDATES = ['docs/diagrams', 'docs/diagram', 'docs/architecture/diagrams', 'docs/design/diagrams', 'diagrams'];
const DIAGRAM_EXT = new Set(['.mmd', '.puml', '.dot', '.d2', '.drawio']);
const RENDER_EXT = new Set(['.svg', '.png', '.pdf']);
const INDEX_HINTS = [/^readme\.md$/i, /register/i, /coverage/i, /timeline/i, /index\.md$/i, /catalog(ue)?/i];

const args = (() => {
  const a = { _: [] };
  const v = process.argv.slice(2);
  for (let i = 0; i < v.length; i++) {
    if (!v[i].startsWith('--')) { a._.push(v[i]); continue; }
    const k = v[i].slice(2), n = v[i + 1];
    a[k] = n === undefined || n.startsWith('--') ? true : (i++, n);
  }
  return a;
})();

const repo = resolve(args.repo ?? process.cwd());
if (!existsSync(repo)) { console.error(`diagram-corpus: --repo not found: ${repo}`); process.exit(2); }

const walk = (dir, out = []) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, out); else out.push(p);
  }
  return out;
};

const root = args.dir ? join(repo, args.dir) : CANDIDATES.map((c) => join(repo, c)).find((p) => existsSync(p) && statSync(p).isDirectory());
if (!root || !existsSync(root)) {
  const msg = { corpus: false, tried: args.dir ? [args.dir] : CANDIDATES };
  console.log(args.json ? JSON.stringify(msg, null, 2) : `no diagrams-as-code corpus found (tried ${msg.tried.join(', ')}) — continue without one`);
  process.exit(0);
}

const files = walk(root);
const rel = (p) => relative(repo, p);

// --- front matter of topic files (id, title, area, sources, verified_commit / worktree)
const topics = [];
const fmScalar = (fm, key) => (fm.match(new RegExp(`^${key}:\\s*(.+)$`, 'm')) ?? [])[1]?.trim().replace(/^["']|["']$/g, '');
const fmList = (fm, key) => {
  const block = fm.match(new RegExp(`^${key}:\\s*(?:\\[(.*?)\\]\\s*$|$([\\s\\S]*?)(?=^\\S|$(?![\\s\\S])))`, 'm'));
  if (!block) return [];
  if (block[1]) return block[1].split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
  return (block[2] ?? '').split('\n').map((l) => (l.match(/^\s+-\s*(.+)$/) ?? [])[1]).filter(Boolean).map((s) => s.trim().replace(/^["']|["']$/g, ''));
};

let diagramBlocks = 0, citations = 0;
const kinds = {}, areas = {}, indexes = [], renders = [], sources = new Set(), markers = {};
const MARKER = /\b(TENSION|DEBT|DRIFT|OPEN|INVARIANT)\b\s*:/g;

for (const f of files) {
  const ext = extname(f).toLowerCase();
  if (RENDER_EXT.has(ext)) { renders.push(f); continue; }
  if (DIAGRAM_EXT.has(ext)) { diagramBlocks++; kinds[ext.slice(1)] = (kinds[ext.slice(1)] ?? 0) + 1; continue; }
  if (ext !== '.md') continue;
  const base = f.split(sep).pop();
  const text = readFileSync(f, 'utf8');
  if (INDEX_HINTS.some((r) => r.test(base))) indexes.push({ path: rel(f), lines: text.split('\n').length, generated: /GENERATED BY/i.test(text.slice(0, 400)) });
  for (const m of text.matchAll(/```(\w+)?\s*\n/g)) {
    const lang = (m[1] ?? '').toLowerCase();
    if (['mermaid', 'plantuml', 'dot', 'd2'].includes(lang)) { diagramBlocks++; kinds[lang] = (kinds[lang] ?? 0) + 1; }
  }
  for (const m of text.matchAll(MARKER)) markers[m[1]] = (markers[m[1]] ?? 0) + 1;
  citations += [...text.matchAll(/[\w./-]+\.[a-z]{1,5}:\d+/g)].length;
  const fmMatch = text.match(/^---\n([\s\S]*?)\n---/);
  if (!fmMatch) continue;
  const fm = fmMatch[1];
  const id = fmScalar(fm, 'id');
  if (!id) continue;
  const src = fmList(fm, 'sources');
  src.forEach((s) => sources.add(s));
  const area = fmScalar(fm, 'area') ?? rel(f).split(sep).slice(-2)[0];
  areas[area] = (areas[area] ?? 0) + 1;
  topics.push({ id, title: fmScalar(fm, 'title') ?? null, area, path: rel(f), sources: src,
    verified_commit: fmScalar(fm, 'verified_commit') ?? fmScalar(fm, 'commit') ?? null, worktree: fmScalar(fm, 'worktree') ?? null });
}

// --- freshness: for each declared revision, which of the topic's own sources moved since
const git = (a) => { try { return execFileSync('git', ['-C', repo, ...a], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); } catch { return null; } };
const head = git(['rev-parse', 'HEAD']);
const changedCache = new Map();
const changedSince = (sha) => {
  if (!sha) return null;
  if (changedCache.has(sha)) return changedCache.get(sha);
  const out = git(['diff', '--name-only', `${sha}..HEAD`]);
  const set = out === null ? null : new Set(out.split('\n').filter(Boolean));
  changedCache.set(sha, set);
  return set;
};
// A declared revision may be a bare sha, `repo@sha`, or a map naming one sha per repository
// (`{a: sha, b: sha}`). Prefer the entry whose key matches this repository's directory name.
const repoName = repo.split(sep).pop();
const bareSha = (v) => {
  if (!v) return null;
  const keyed = [...v.matchAll(/([\w.-]+)\s*[@:]\s*([0-9a-f]{7,40})/g)];
  if (keyed.length) return (keyed.find(([, k]) => k === repoName) ?? keyed[0])[2];
  return (v.match(/\b[0-9a-f]{7,40}\b/) ?? [null])[0];
};
for (const t of topics) {
  const bare = bareSha(t.verified_commit);
  const changed = changedSince(bare);
  t.stale = changed === null ? null : t.sources.filter((s) => changed.has(s));
  t.unresolved_revision = bare != null && changed === null;
}

const tools = files.filter((f) => /\/tools?\//.test(f) && ['.cjs', '.mjs', '.js', '.py', '.sh'].includes(extname(f))).map(rel);
const staleTopics = topics.filter((t) => (t.stale ?? []).length > 0);
const summary = {
  corpus: true, root: rel(root), head,
  files: files.length, topic_count: topics.length, diagrams: diagramBlocks, kinds,
  rendered: renders.length, areas, indexes, tools,
  distinct_sources: sources.size, citations, markers,
  revisions: [...new Set(topics.map((t) => t.verified_commit).filter(Boolean))],
  stale_topics: staleTopics.length, unresolved_revisions: topics.filter((t) => t.unresolved_revision).length,
  topics: args['stale-only'] ? staleTopics : topics,
};

if (args.json) { console.log(JSON.stringify(summary, null, 2)); process.exit(0); }
const limit = Number(args.limit ?? 12);
console.log(`corpus ${summary.root} — ${summary.topic_count} topic files, ${diagramBlocks} diagrams (${Object.entries(kinds).map(([k, v]) => `${k} ${v}`).join(', ') || 'none'}), ${renders.length} rendered, ${citations} source citations`);
console.log(`areas: ${Object.entries(areas).map(([a, n]) => `${a} ${n}`).join(' · ') || 'none declared'}`);
if (indexes.length) console.log(`indexes: ${indexes.map((i) => `${i.path}${i.generated ? ' (generated)' : ''}`).join(', ')}`);
if (tools.length) console.log(`tools: ${tools.join(', ')}`);
if (Object.keys(markers).length) console.log(`register markers: ${Object.entries(markers).map(([k, v]) => `${k} ${v}`).join(' · ')}`);
console.log(`declared revisions: ${summary.revisions.join(', ') || 'none'}${head ? ` · HEAD ${head.slice(0, 7)}` : ''}`);
if (staleTopics.length) {
  console.log(`\n${staleTopics.length} topic(s) cite sources that changed since their declared revision — re-verify before reusing their claims:`);
  for (const t of staleTopics.slice(0, limit)) console.log(`  ${t.id} ${t.path} — ${t.stale.length} moved: ${t.stale.slice(0, 4).join(', ')}${t.stale.length > 4 ? ' …' : ''}`);
  if (staleTopics.length > limit) console.log(`  … and ${staleTopics.length - limit} more (--json for all)`);
} else if (head) console.log('\nno topic cites a source that moved since its declared revision');
if (summary.unresolved_revisions) console.log(`${summary.unresolved_revisions} topic(s) declare a revision this repository cannot resolve`);
