title = "Gitleaks Config"
useDefault = true

[allowlist]
files = [
  '(?:^|/)\.env\.example$',
  '(?:^|/)\.env\.template$'
]

paths = [
  '(?:^|/)\.env\.example$',
  '(?:^|/)\.env\.template$'
]

regexes = [
  "AKIA.*EXAMPLE"
]
