#!/bin/bash
# Agentbox Quick Connect Script
# Auto-generated by Oracle Cloud deployment

set -euo pipefail

# Instance configuration - updated by provision-oci.sh
AGENTBOX_IP=""
AGENTBOX_USER="opc"
SSH_KEY="$HOME/.ssh/agentbox_key"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

usage() {
    cat << EOF
${CYAN}Agentbox - Oracle Cloud ARM Instance Manager${NC}

Usage: $0 <command> [options]

Commands:
  ${GREEN}ssh${NC}              Connect via SSH
  ${GREEN}vnc${NC}              Open VNC tunnel (localhost:5901)
  ${GREEN}browser${NC}          Open browser tunnels (VNC + Chrome DevTools)
  ${GREEN}code${NC}             Open code-server tunnel (localhost:8080)
  ${GREEN}api${NC}              Open Management API tunnel (localhost:9090)
  ${GREEN}all${NC}              Open all tunnels (VNC, code-server, API, CDP)
  ${GREEN}status${NC}           Check instance status
  ${GREEN}provision${NC}        Provision new instance (loops until capacity)
  ${GREEN}ip${NC}               Show instance IP
  ${GREEN}setup${NC}            Run initial setup on instance
  ${GREEN}start-browser${NC}    Start visible browser on remote (for agent-browser)

Options:
  -i, --ip IP      Override instance IP
  -h, --help       Show this help

Examples:
  $0 ssh                    # Connect via SSH
  $0 vnc                    # Start VNC tunnel, then connect to vnc://localhost:5901
  $0 all                    # Start all tunnels
  $0 provision --loop       # Keep trying until capacity available

EOF
}

check_ip() {
    if [[ -z "$AGENTBOX_IP" ]]; then
        # Try to read from cached IP
        if [[ -f /tmp/agentbox-ip.txt ]]; then
            AGENTBOX_IP=$(cat /tmp/agentbox-ip.txt)
        else
            echo -e "${RED}Error: No instance IP configured.${NC}"
            echo "Run: $0 provision"
            exit 1
        fi
    fi
}

cmd_ssh() {
    check_ip
    echo -e "${CYAN}Connecting to agentbox@${AGENTBOX_IP}...${NC}"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$AGENTBOX_USER@$AGENTBOX_IP" "$@"
}

cmd_vnc() {
    check_ip
    echo -e "${CYAN}Starting VNC tunnel to ${AGENTBOX_IP}:5901...${NC}"
    echo -e "${GREEN}Connect to: vnc://localhost:5901${NC}"
    ssh -i "$SSH_KEY" -N -L 5901:localhost:5901 "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_code() {
    check_ip
    echo -e "${CYAN}Starting code-server tunnel to ${AGENTBOX_IP}:8080...${NC}"
    echo -e "${GREEN}Open: http://localhost:8080${NC}"
    ssh -i "$SSH_KEY" -N -L 8080:localhost:8080 "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_api() {
    check_ip
    echo -e "${CYAN}Starting Management API tunnel to ${AGENTBOX_IP}:9090...${NC}"
    echo -e "${GREEN}Open: http://localhost:9090${NC}"
    ssh -i "$SSH_KEY" -N -L 9090:localhost:9090 "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_browser() {
    check_ip
    echo -e "${CYAN}Starting browser automation tunnels to ${AGENTBOX_IP}...${NC}"
    echo -e "${GREEN}VNC Desktop:     vnc://localhost:5901${NC}"
    echo -e "${GREEN}Chrome DevTools: http://localhost:9222${NC}"
    echo ""
    echo -e "${YELLOW}Usage:${NC}"
    echo "  1. Start browser on remote: $0 start-browser"
    echo "  2. Use agent-browser locally: agent-browser open https://example.com"
    echo ""
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new -N \
        -L 5901:localhost:5901 \
        -L 9222:localhost:9222 \
        "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_all() {
    check_ip
    echo -e "${CYAN}Starting all tunnels to ${AGENTBOX_IP}...${NC}"
    echo -e "${GREEN}VNC Desktop:     vnc://localhost:5901${NC}"
    echo -e "${GREEN}code-server:     http://localhost:8080${NC}"
    echo -e "${GREEN}Management API:  http://localhost:9090${NC}"
    echo -e "${GREEN}Chrome DevTools: http://localhost:9222${NC}"
    echo ""
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new -N \
        -L 5901:localhost:5901 \
        -L 8080:localhost:8080 \
        -L 9090:localhost:9090 \
        -L 9222:localhost:9222 \
        "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_status() {
    check_ip
    echo -e "${CYAN}Checking agentbox status...${NC}"
    ssh -i "$SSH_KEY" -o ConnectTimeout=5 "$AGENTBOX_USER@$AGENTBOX_IP" \
        "uptime && free -h && df -h / && docker ps 2>/dev/null | head -5 || true" 2>&1 || \
        echo -e "${RED}Instance unreachable${NC}"
}

cmd_ip() {
    check_ip
    echo "$AGENTBOX_IP"
}

cmd_provision() {
    SCRIPT_DIR="$(dirname "$0")"
    if [[ -f "$SCRIPT_DIR/scripts/provision-oci.sh" ]]; then
        exec "$SCRIPT_DIR/scripts/provision-oci.sh" "$@"
    else
        echo -e "${RED}Provisioning script not found${NC}"
        exit 1
    fi
}

cmd_start_browser() {
    check_ip
    echo -e "${CYAN}Starting visible browser on ${AGENTBOX_IP}...${NC}"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$AGENTBOX_USER@$AGENTBOX_IP" \
        'export DISPLAY=:1; chromium --no-sandbox --remote-debugging-port=9222 --user-data-dir=$HOME/.config/chromium-automation --window-size=1920,1080 --disable-gpu &'
    echo -e "${GREEN}Browser started with Chrome DevTools on port 9222${NC}"
    echo ""
    echo "Now run: $0 browser"
    echo "Then:    agent-browser open https://example.com"
}

cmd_setup() {
    check_ip
    echo -e "${CYAN}Running initial setup on agentbox...${NC}"

    # Copy setup script and run
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$AGENTBOX_USER@$AGENTBOX_IP" << 'SETUP_EOF'
#!/bin/bash
set -e

echo "=== Agentbox Initial Setup ==="

# Update system
sudo dnf update -y

# Install Docker
sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo systemctl enable --now docker
sudo usermod -aG docker $USER

# Install development tools
sudo dnf install -y git nodejs npm python3-pip tmux htop

# Install VNC stack
echo "Installing VNC desktop..."
sudo dnf install -y xorg-x11-server-Xvfb x11vnc openbox xterm chromium

# Install agent-browser and playwright
echo "Installing browser automation tools..."
sudo npm install -g agent-browser playwright
sudo npx playwright install chromium

# Create VNC startup script
cat > ~/start-vnc.sh << 'VNCSCRIPT'
#!/bin/bash
export DISPLAY=:1
rm -f /tmp/.X*-lock /tmp/.X11-unix/X* 2>/dev/null
Xvfb :1 -screen 0 4096x4096x24 -ac +extension GLX +render -noreset &
sleep 2
openbox &
x11vnc -display :1 -rfbport 5901 -forever -shared -nopw -xkb -localhost &
echo "VNC started on localhost:5901 (use SSH tunnel)"
VNCSCRIPT
chmod +x ~/start-vnc.sh

# Create browser startup script
cat > ~/start-browser.sh << 'BROWSERSCRIPT'
#!/bin/bash
export DISPLAY=:1
chromium --no-sandbox --remote-debugging-port=9222 \
  --user-data-dir=$HOME/.config/chromium-automation \
  --window-size=1920,1080 --disable-gpu "$@" &
echo "Browser started with CDP on port 9222"
BROWSERSCRIPT
chmod +x ~/start-browser.sh

# Open firewall ports (localhost only for VNC/CDP)
sudo firewall-cmd --permanent --add-port=22/tcp
sudo firewall-cmd --permanent --add-port=8080/tcp
sudo firewall-cmd --permanent --add-port=9090/tcp
sudo firewall-cmd --reload

# Start VNC
~/start-vnc.sh

echo "=== Setup complete! ==="
echo ""
echo "VNC: Use SSH tunnel - ssh -L 5901:localhost:5901 $USER@hostname"
echo "Browser: ~/start-browser.sh, then agent-browser open <url>"
SETUP_EOF

    echo -e "${GREEN}Setup complete!${NC}"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -i|--ip)
            AGENTBOX_IP="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        ssh|vnc|browser|code|api|all|status|ip|provision|setup|start-browser)
            CMD="$1"
            shift
            break
            ;;
        *)
            echo -e "${RED}Unknown command: $1${NC}"
            usage
            exit 1
            ;;
    esac
done

# Execute command
case "${CMD:-}" in
    ssh)           cmd_ssh "$@" ;;
    vnc)           cmd_vnc ;;
    browser)       cmd_browser ;;
    code)          cmd_code ;;
    api)           cmd_api ;;
    all)           cmd_all ;;
    status)        cmd_status ;;
    ip)            cmd_ip ;;
    provision)     cmd_provision "$@" ;;
    setup)         cmd_setup ;;
    start-browser) cmd_start_browser ;;
    *)             usage ;;
esac
