#!/bin/bash
# Agentbox Quick Connect Script
# Auto-generated by Oracle Cloud deployment

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Instance configuration - updated by provision-oci.sh
AGENTBOX_IP=""
AGENTBOX_USER="opc"
SSH_KEY="$HOME/.ssh/agentbox_key"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

usage() {
    cat << EOF
${CYAN}Agentbox - Oracle Cloud ARM Instance Manager${NC}

Usage: $0 <command> [options]

Remote operator commands:
  ${GREEN}ssh${NC}              Connect via SSH
  ${GREEN}vnc${NC}              Open VNC tunnel (localhost:5901)
  ${GREEN}browser${NC}          Open browser tunnels (VNC + Chrome DevTools)
  ${GREEN}code${NC}             Open code-server tunnel (localhost:8080)
  ${GREEN}api${NC}              Open Management API tunnel (localhost:9090)
  ${GREEN}all${NC}              Open all tunnels (VNC, code-server, API, CDP)
  ${GREEN}status${NC}           Check instance status
  ${GREEN}provision${NC}        Provision new instance [--target oci|fly|hetzner|bare] (default: oci)
  ${GREEN}ip${NC}               Show instance IP
  ${GREEN}setup${NC}            Run initial setup on instance
  ${GREEN}start-browser${NC}    Start visible browser on remote (for agent-browser)
  ${GREEN}backup${NC}           Backup named volumes and config to a tarball
  ${GREEN}restore${NC}          Restore named volumes and config from a tarball

Local lifecycle commands:
  ${GREEN}up${NC}               Start the Docker stack [--build: nix build + docker load first] [--registry: use AGENTBOX_IMAGE_REF from env]
  ${GREEN}down${NC}             Stop the Docker stack [--volumes: also remove volumes (confirms)]
  ${GREEN}build${NC}            Build the Nix image [--variant runtime|desktop|full]
  ${GREEN}rebuild${NC}          Full dev-loop cycle: down + build + up --build
  ${GREEN}update${NC}           Update flake inputs + npm CLI versions + resolve hashes [--check|--npm-only|--flake-only]
  ${GREEN}ruvector${NC}         Manage the ruvector-postgres memory sidecar [status|check|test|update|rollback|migrate-trajectories|repair-namespaces|backfill-embeddings|archive-legacy|aggregate-effectiveness|build-metadata-gin]
  ${GREEN}logs${NC}             Follow logs [service: supervisorctl tail, else compose logs]
  ${GREEN}shell${NC}            Open shell in container [profile: zellij layout in that profile]
  ${GREEN}health${NC}           Show service health [--json: raw JSON output]
  ${GREEN}migrate-workspace${NC} One-shot rsync from legacy multi-agent-docker_workspace into agentbox-workspace, then patch override
  ${GREEN}browsercontainer${NC} Manage GPU browser container [up|down|logs|health|status|rebuild|shell|gpu]
  ${GREEN}gui-tools${NC}        Manage GPU Blender + QGIS sidecar [up|down|logs|health|status|rebuild|shell|gpu]
  ${GREEN}openmed${NC}          Manage optional clinical-PHI redaction sidecar [up|down|logs|health|status|rebuild|shell]
  ${GREEN}voice${NC}            Manage voice + AoE operator console (Caddy :8444) + Unmute stack [up|down|logs|health|status|certs|rebuild|shell]
  ${GREEN}xr-runtime${NC}       Manage Monado OpenXR + Godot XR test runtime [up|down|logs|health|status|rebuild|shell|gpu|vnc]
  ${GREEN}android${NC}          [EXPERIMENTAL, gated] redroid Android/Play sidecar [up|down|logs|status|screencap|shell|id] — needs AGENTBOX_ENABLE_ANDROID=1
  ${GREEN}preflight${NC}        Validate the local environment + manifest before up (W021 audit, missing host paths, override drift)

Options:
  -i, --ip IP      Override instance IP
  -h, --help       Show this help

Examples:
  $0 ssh                    # Connect via SSH
  $0 vnc                    # Start VNC tunnel, then connect to vnc://localhost:5901
  $0 all                    # Start all tunnels
  $0 provision --loop                   # OCI (default), keep retrying
  $0 provision --target oci --loop     # Explicit OCI target
  $0 provision --target bare --host ubuntu@192.168.1.10
  $0 backup                 # Create timestamped backup in ./backups/
  $0 backup --out /tmp/snap.tgz --include-secrets
  $0 restore ./backups/agentbox-backup-20260101T000000Z.tgz
  $0 restore ./backups/agentbox-backup-20260101T000000Z.tgz --force
  $0 up                     # Start stack, poll health, print summary
  $0 up --build             # Nix build + docker load, then start
  $0 up --registry          # Use AGENTBOX_IMAGE_REF from env (must be set; registry image)
  $0 down                   # Stop stack
  $0 down --volumes         # Stop stack and remove volumes (destructive, confirms)
  $0 build --variant full   # Build the full image without loading it
  $0 rebuild                # down + build + up (dev-loop iteration)
  $0 update                 # full update: flake inputs (nixpkgs etc.) + npm CLI versions + resolve hashes
  $0 update --check         # report available updates without patching
  $0 ruvector check         # compare running sidecar + pinned image against Docker Hub
  $0 ruvector update        # gated sidecar update: dump + snapshot + candidate rehearsal + swap
  $0 ruvector rollback      # revert the last sidecar update from its snapshot
  $0 ruvector migrate-trajectories       # additive learning-loop schema (dry-run; --yes applies)
  $0 ruvector repair-namespaces          # dry-run un-swap of 178k namespace<->value rows (--yes + [memory_hygiene] flag)
  $0 ruvector backfill-embeddings        # dry-run NULL-embedding backfill via Xinference (--yes + flag)
  $0 ruvector archive-legacy             # dry-run archive+delete of ~1.84M frozen legacy rows (--yes + flag)
  $0 ruvector aggregate-effectiveness    # dry-run Wilson+recency effectiveness aggregates (--yes + [memory_learning] enabled)
  $0 ruvector build-metadata-gin         # dry-run GIN on metadata jsonb_path_ops for tag @> (--yes + metadata_gin flag)
  $0 ruvnet-brain ingest    # reconcile RuvNet KB corpus in the sidecar against latest release (--force to re-embed all)
  $0 ruvnet-brain status    # corpus chunk count + ingest manifest (namespace ruvnet-kb)
  $0 ruvnet-brain logs      # follow the boot-time ingest log
  $0 update --flake-only    # only update flake inputs (nixpkgs, rust-overlay, etc.)
  $0 update --npm-only      # only bump npm CLI versions in flake.nix
  $0 logs                   # Follow all service logs
  $0 logs management-api    # Follow a specific service via supervisorctl
  $0 shell                  # bash in the agentbox container
  $0 shell ruflo-orchestrator  # zellij layout for a profile
  $0 health                 # Pretty-print service health
  $0 health --json          # Raw JSON health response

EOF
}

check_ip() {
    if [[ -z "$AGENTBOX_IP" ]]; then
        # Try to read from cached IP
        if [[ -f /tmp/agentbox-ip.txt ]]; then
            AGENTBOX_IP=$(cat /tmp/agentbox-ip.txt)
        else
            echo -e "${RED}Error: No instance IP configured.${NC}"
            echo "Run: $0 provision"
            exit 1
        fi
    fi
}

cmd_ssh() {
    check_ip
    echo -e "${CYAN}Connecting to agentbox@${AGENTBOX_IP}...${NC}"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$AGENTBOX_USER@$AGENTBOX_IP" "$@"
}

cmd_vnc() {
    check_ip
    echo -e "${CYAN}Starting VNC tunnel to ${AGENTBOX_IP}:5901...${NC}"
    echo -e "${GREEN}Connect to: vnc://localhost:5901${NC}"
    ssh -i "$SSH_KEY" -N -L 5901:localhost:5901 "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_code() {
    check_ip
    echo -e "${CYAN}Starting code-server tunnel to ${AGENTBOX_IP}:8080...${NC}"
    echo -e "${GREEN}Open: http://localhost:8080${NC}"
    ssh -i "$SSH_KEY" -N -L 8080:localhost:8080 "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_api() {
    check_ip
    echo -e "${CYAN}Starting Management API tunnel to ${AGENTBOX_IP}:9090...${NC}"
    echo -e "${GREEN}Open: http://localhost:9090${NC}"
    ssh -i "$SSH_KEY" -N -L 9090:localhost:9090 "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_browser() {
    check_ip
    echo -e "${CYAN}Starting browser automation tunnels to ${AGENTBOX_IP}...${NC}"
    echo -e "${GREEN}VNC Desktop:     vnc://localhost:5901${NC}"
    echo -e "${GREEN}Chrome DevTools: http://localhost:9222${NC}"
    echo ""
    echo -e "${YELLOW}Usage:${NC}"
    echo "  1. Start browser on remote: $0 start-browser"
    echo "  2. Use agent-browser locally: agent-browser open https://example.com"
    echo ""
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new -N \
        -L 5901:localhost:5901 \
        -L 9222:localhost:9222 \
        "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_all() {
    check_ip
    echo -e "${CYAN}Starting all tunnels to ${AGENTBOX_IP}...${NC}"
    echo -e "${GREEN}VNC Desktop:     vnc://localhost:5901${NC}"
    echo -e "${GREEN}code-server:     http://localhost:8080${NC}"
    echo -e "${GREEN}Management API:  http://localhost:9090${NC}"
    echo -e "${GREEN}Chrome DevTools: http://localhost:9222${NC}"
    echo ""
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new -N \
        -L 5901:localhost:5901 \
        -L 8080:localhost:8080 \
        -L 9090:localhost:9090 \
        -L 9222:localhost:9222 \
        "$AGENTBOX_USER@$AGENTBOX_IP"
}

cmd_status() {
    check_ip
    echo -e "${CYAN}Checking agentbox status...${NC}"
    ssh -i "$SSH_KEY" -o ConnectTimeout=5 "$AGENTBOX_USER@$AGENTBOX_IP" \
        "uptime && free -h && df -h / && docker ps 2>/dev/null | head -5 || true" 2>&1 || \
        echo -e "${RED}Instance unreachable${NC}"
}

cmd_ip() {
    check_ip
    echo "$AGENTBOX_IP"
}

cmd_provision() {
    local target="oci"
    local passthrough=()

    while [[ $# -gt 0 ]]; do
        case $1 in
            --target) target="$2"; shift 2 ;;
            *) passthrough+=("$1"); shift ;;
        esac
    done

    local provisioner="$SCRIPT_DIR/scripts/provision-${target}.sh"

    case "$target" in
        oci|fly|hetzner|bare) ;;
        *)
            echo -e "${RED}Unknown provisioning target: ${target}${NC}"
            echo "Available targets: oci, fly, hetzner, bare"
            echo "Usage: $0 provision [--target <target>] [target-specific options]"
            exit 1
            ;;
    esac

    if [[ ! -f "$provisioner" ]]; then
        echo -e "${RED}Provisioner not found: ${provisioner}${NC}"
        exit 1
    fi

    exec "$provisioner" "${passthrough[@]+"${passthrough[@]}"}"
}

cmd_start_browser() {
    check_ip
    echo -e "${CYAN}Starting visible browser on ${AGENTBOX_IP}...${NC}"
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$AGENTBOX_USER@$AGENTBOX_IP" \
        'export DISPLAY=:1; chromium --no-sandbox --remote-debugging-port=9222 --user-data-dir=$HOME/.config/chromium-automation --window-size=1920,1080 --disable-gpu &'
    echo -e "${GREEN}Browser started with Chrome DevTools on port 9222${NC}"
    echo ""
    echo "Now run: $0 browser"
    echo "Then:    agent-browser open https://example.com"
}

# ---------------------------------------------------------------------------
# backup / restore helpers
# ---------------------------------------------------------------------------

# Dump a single named Docker volume into a tar stream via a throw-away alpine
# helper container.  Caller receives the stream on stdout.
_volume_tar() {
    local volume_name="$1"
    docker run --rm \
        -v "${volume_name}:/data:ro" \
        alpine:3.20 \
        tar -C /data -cf - .
}

# Restore a tar stream (from stdin) into a named Docker volume.
_volume_untar() {
    local volume_name="$1"
    docker run --rm -i \
        -v "${volume_name}:/data" \
        alpine:3.20 \
        sh -c 'tar -C /data -xf -'
}

# Return 0 iff the agentbox.toml pods adapter is backed by local storage
# under /var/lib/solid (local-solid-rs first-class Rust server, ADR-010).
# Used to decide whether the solid-data volume goes into backups.
_solid_is_local() {
    local toml="${SCRIPT_DIR}/agentbox.toml"
    [[ -f "$toml" ]] && \
      grep -qE '^\s*pods\s*=\s*"local-solid-rs"' "$toml"
}

cmd_backup() {
    local out="" include_secrets=0
    while [[ $# -gt 0 ]]; do
        case $1 in
            --out)       out="$2";        shift 2 ;;
            --include-secrets) include_secrets=1; shift ;;
            *) echo -e "${RED}Unknown backup option: $1${NC}"; exit 1 ;;
        esac
    done

    local timestamp
    timestamp=$(date -u +%Y%m%dT%H%M%SZ)

    if [[ -z "$out" ]]; then
        mkdir -p "${SCRIPT_DIR}/backups"
        out="${SCRIPT_DIR}/backups/agentbox-backup-${timestamp}.tgz"
    fi

    local work
    work=$(mktemp -d)
    trap 'rm -rf "$work"' EXIT

    echo -e "${CYAN}Backing up agentbox volumes and config...${NC}"

    # -- ruvector-data (always) -----------------------------------------------
    echo -e "  ${GREEN}+${NC} ruvector-data"
    mkdir -p "${work}/volumes/ruvector-data"
    _volume_tar agentbox-ruvector-data | tar -C "${work}/volumes/ruvector-data" -xf - 2>/dev/null || true

    # -- ruvector-postgres logical dump (PRD-018 Phase 0, closes gap #12) -----
    # The memory DB (2M+ rows on ruvector_postgres_data_v2) was previously
    # absent from backups entirely. A raw volume tar of a live PG datadir is
    # not crash-consistent, so the backup carries a pg_dump -Fc instead;
    # restore replays it via pg_restore once the sidecar is back up.
    local rv_pg_dumped=0
    if docker exec ruvector-postgres pg_isready -U ruvector -d ruvector >/dev/null 2>&1; then
        echo -e "  ${GREEN}+${NC} ruvector-postgres (pg_dump -Fc — 2M+ rows, may take minutes)"
        if docker exec ruvector-postgres pg_dump -U ruvector -Fc ruvector > "${work}/ruvector-pg.dump" 2>/dev/null; then
            rv_pg_dumped=1
        else
            rm -f "${work}/ruvector-pg.dump"
            echo -e "  ${YELLOW}!${NC} pg_dump failed — memory DB NOT included in this backup"
        fi
    else
        echo -e "  ${YELLOW}!${NC} ruvector-postgres not running — memory DB NOT included in this backup"
    fi

    # -- solid-data (when pods = local-solid-rs) ------------------------------
    # solid-pod-rs (ADR-010) stores under /var/lib/solid. See docs/user/backup-restore.md.
    local solid_included=0
    if _solid_is_local; then
        echo -e "  ${GREEN}+${NC} solid-data"
        mkdir -p "${work}/volumes/solid-data"
        _volume_tar agentbox-solid-data | tar -C "${work}/volumes/solid-data" -xf - 2>/dev/null || true
        solid_included=1
    fi

    # -- sovereign-identities (only with --include-secrets) -------------------
    local secrets_included=0
    if [[ "$include_secrets" -eq 1 ]]; then
        echo -e "  ${YELLOW}+${NC} sovereign-identities (secrets included)"
        mkdir -p "${work}/volumes/sovereign-identities"
        _volume_tar agentbox-sovereign-identities | tar -C "${work}/volumes/sovereign-identities" -xf - 2>/dev/null || true
        secrets_included=1
    fi

    # -- agentbox.toml --------------------------------------------------------
    if [[ -f "${SCRIPT_DIR}/agentbox.toml" ]]; then
        echo -e "  ${GREEN}+${NC} agentbox.toml"
        cp "${SCRIPT_DIR}/agentbox.toml" "${work}/agentbox.toml"
    fi

    # -- supervisord.conf from running container (best-effort) ----------------
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q '^agentbox$'; then
        echo -e "  ${GREEN}+${NC} supervisord.conf"
        docker cp agentbox:/etc/supervisord.conf "${work}/supervisord.conf" 2>/dev/null || true
    fi

    # -- workspace/profiles (bind-mount path) — exclude secrets by default ---
    local profiles_dir="${SCRIPT_DIR}/workspace/profiles"
    if [[ -d "$profiles_dir" ]]; then
        echo -e "  ${GREEN}+${NC} workspace/profiles (mgmt-keys $([ "$include_secrets" -eq 1 ] && echo 'INCLUDED' || echo 'excluded'))"
        if [[ "$include_secrets" -eq 1 ]]; then
            cp -a "$profiles_dir" "${work}/profiles"
        else
            # Exclude key/pem/env/mgmt-key files
            mkdir -p "${work}/profiles"
            if command -v rsync >/dev/null 2>&1; then
                rsync -a \
                    --exclude='*.key' \
                    --exclude='*.pem' \
                    --exclude='*.env' \
                    --exclude='mgmt-key' \
                    "${profiles_dir}/" "${work}/profiles/"
            else
                tar -C "${profiles_dir}" \
                    --exclude='*.key' --exclude='*.pem' --exclude='*.env' --exclude='mgmt-key' \
                    -cf - . | tar -C "${work}/profiles" -xf -
                if [[ ${PIPESTATUS[0]} -ne 0 || ${PIPESTATUS[1]} -ne 0 ]]; then
                    echo -e "${RED}ERROR: profile backup failed — neither rsync nor tar succeeded${NC}"
                    exit 1
                fi
            fi
        fi
    fi

    # -- MANIFEST.json --------------------------------------------------------
    local file_count total_size
    file_count=$(find "${work}" -type f | wc -l)
    total_size=$(du -sh "${work}" 2>/dev/null | cut -f1 || echo "unknown")

    cat > "${work}/MANIFEST.json" <<EOF
{
  "version": "1",
  "timestamp": "${timestamp}",
  "include_secrets": ${include_secrets},
  "solid_included": ${solid_included},
  "contents": {
    "ruvector_data": true,
    "ruvector_pg_dump": $([ "$rv_pg_dumped" -eq 1 ] && echo true || echo false),
    "solid_data": ${solid_included},
    "sovereign_identities": ${secrets_included},
    "agentbox_toml": $([ -f "${work}/agentbox.toml" ] && echo true || echo false),
    "supervisord_conf": $([ -f "${work}/supervisord.conf" ] && echo true || echo false),
    "profiles": $([ -d "${work}/profiles" ] && echo true || echo false)
  },
  "exclusions": {
    "default": ["*.key", "*.pem", "*.env", "mgmt-key", "sovereign-identities"],
    "secrets_flag_required": ["sovereign-identities", "mgmt-key"]
  }
}
EOF

    # Recount after manifest is written
    file_count=$(find "${work}" -type f | wc -l)

    # -- pack -----------------------------------------------------------------
    tar -C "${work}" -czf "${out}" .

    local archive_size
    archive_size=$(du -sh "${out}" 2>/dev/null | cut -f1 || echo "unknown")

    echo ""
    echo -e "${GREEN}Backup complete${NC}"
    echo -e "  Archive : ${out}"
    echo -e "  Files   : ${file_count}"
    echo -e "  Size    : ${archive_size}"
    echo -e "  Secrets : $([ "$include_secrets" -eq 1 ] && echo 'INCLUDED' || echo 'excluded (use --include-secrets to include)')"

    trap - EXIT
    rm -rf "$work"
}

cmd_restore() {
    local tarfile="" force=0
    while [[ $# -gt 0 ]]; do
        case $1 in
            --force) force=1; shift ;;
            -*)      echo -e "${RED}Unknown restore option: $1${NC}"; exit 1 ;;
            *)       tarfile="$1"; shift ;;
        esac
    done

    if [[ -z "$tarfile" ]]; then
        echo -e "${RED}Usage: $0 restore <tarfile> [--force]${NC}"
        exit 1
    fi

    if [[ ! -f "$tarfile" ]]; then
        echo -e "${RED}Archive not found: ${tarfile}${NC}"
        exit 1
    fi

    local work
    work=$(mktemp -d)
    trap 'rm -rf "$work"' EXIT

    # -- unpack ---------------------------------------------------------------
    echo -e "${CYAN}Unpacking archive...${NC}"
    tar -C "${work}" -xzf "${tarfile}"

    # -- validate manifest ----------------------------------------------------
    if [[ ! -f "${work}/MANIFEST.json" ]]; then
        echo -e "${RED}Invalid archive: missing MANIFEST.json${NC}"
        exit 1
    fi

    local manifest_ts manifest_version
    manifest_version=$(jq -r '.version // "unknown"' "${work}/MANIFEST.json")
    manifest_ts=$(jq -r '.timestamp // "unknown"'   "${work}/MANIFEST.json")

    echo -e "  Manifest version : ${manifest_version}"
    echo -e "  Backup timestamp : ${manifest_ts}"
    echo ""

    # -- confirm --------------------------------------------------------------
    if [[ "$force" -eq 0 ]]; then
        echo -e "${YELLOW}WARNING: This will overwrite the following named volumes:${NC}"
        jq -r '
          .contents | to_entries[]
          | select(.value == true)
          | "  - " + .key
        ' "${work}/MANIFEST.json"
        echo ""
        printf "Proceed? [y/N] "
        read -r answer
        case "$answer" in
            y|Y|yes|YES) ;;
            *) echo "Aborted."; exit 0 ;;
        esac
    fi

    # -- stop stack -----------------------------------------------------------
    echo -e "${CYAN}Stopping stack...${NC}"
    docker compose "${COMPOSE_ARGS[@]}" down 2>/dev/null || true

    # -- restore volumes ------------------------------------------------------
    if [[ -d "${work}/volumes/ruvector-data" ]]; then
        echo -e "  ${GREEN}*${NC} Restoring ruvector-data"
        docker volume create agentbox-ruvector-data 2>/dev/null || true
        tar -C "${work}/volumes/ruvector-data" -cf - . | _volume_untar agentbox-ruvector-data
    fi

    if [[ -d "${work}/volumes/solid-data" ]]; then
        echo -e "  ${GREEN}*${NC} Restoring solid-data"
        docker volume create agentbox-solid-data 2>/dev/null || true
        tar -C "${work}/volumes/solid-data" -cf - . | _volume_untar agentbox-solid-data
    fi

    if [[ -d "${work}/volumes/sovereign-identities" ]]; then
        echo -e "  ${YELLOW}*${NC} Restoring sovereign-identities"
        docker volume create agentbox-sovereign-identities 2>/dev/null || true
        tar -C "${work}/volumes/sovereign-identities" -cf - . | _volume_untar agentbox-sovereign-identities
    fi

    # -- restore agentbox.toml ------------------------------------------------
    if [[ -f "${work}/agentbox.toml" ]]; then
        echo -e "  ${GREEN}*${NC} Restoring agentbox.toml"
        cp "${work}/agentbox.toml" "${SCRIPT_DIR}/agentbox.toml"
    fi

    # -- restore profiles (bind mount) ----------------------------------------
    if [[ -d "${work}/profiles" ]]; then
        local profiles_dest="${SCRIPT_DIR}/workspace/profiles"
        echo -e "  ${GREEN}*${NC} Restoring workspace/profiles"
        mkdir -p "${profiles_dest}"
        rsync -a "${work}/profiles/" "${profiles_dest}/" 2>/dev/null || \
        tar -C "${work}/profiles" -cf - . | tar -C "${profiles_dest}" -xf -
    fi

    # -- restart stack --------------------------------------------------------
    # COMPOSE_ARGS includes docker-compose.override.yml when present — the
    # override carries RUVECTOR_PG_CONNINFO/RUVECTOR_PG_PASSWORD into the
    # agentbox service; a bare -f docker-compose.yml would silently downgrade
    # the memory sidecar connection to the default password.
    echo -e "${CYAN}Restarting stack...${NC}"
    docker compose "${COMPOSE_ARGS[@]}" up -d

    # -- restore ruvector-postgres memory DB (PRD-018 Phase 0) ----------------
    # pg_restore --clean replaces the current contents with the dump. The
    # operator already confirmed the restore above; this replays the memory DB
    # into the running sidecar once it accepts connections.
    if [[ -f "${work}/ruvector-pg.dump" ]]; then
        echo -e "  ${GREEN}*${NC} Restoring ruvector-postgres memory DB (pg_restore --clean)"
        local rv_deadline=$(( $(date +%s) + 120 ))
        local rv_ready=0
        while [[ $(date +%s) -lt $rv_deadline ]]; do
            if docker exec ruvector-postgres pg_isready -U ruvector -d ruvector >/dev/null 2>&1; then
                rv_ready=1; break
            fi
            sleep 2
        done
        if [[ "$rv_ready" -eq 1 ]] && docker exec -i ruvector-postgres \
                pg_restore -U ruvector -d ruvector --clean --if-exists < "${work}/ruvector-pg.dump" 2>/dev/null; then
            echo -e "  ${GREEN}*${NC} Memory DB restored"
        else
            echo -e "  ${YELLOW}!${NC} pg_restore failed or sidecar not ready — memory DB NOT restored."
            echo -e "    Replay manually: docker exec -i ruvector-postgres pg_restore -U ruvector -d ruvector --clean --if-exists < ruvector-pg.dump"
        fi
    fi

    echo ""
    echo -e "${GREEN}Restore complete.${NC}"

    trap - EXIT
    rm -rf "$work"
}

# ---------------------------------------------------------------------------
# local lifecycle commands
# ---------------------------------------------------------------------------

OVERRIDE_FILE="${SCRIPT_DIR}/docker-compose.override.yml"
COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
SIDECAR_FILE="${SCRIPT_DIR}/docker-compose.browsercontainer.yml"
if [[ -f "$OVERRIDE_FILE" ]]; then
    COMPOSE_ARGS=(--project-name agentbox -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE")
else
    COMPOSE_ARGS=(--project-name agentbox -f "$COMPOSE_FILE")
fi
SIDECAR_COMPOSE_ARGS=(--project-name agentbox -f "$SIDECAR_FILE")
XR_RUNTIME_FILE="${SCRIPT_DIR}/docker-compose.xr-runtime.yml"
XR_RUNTIME_COMPOSE_ARGS=(--project-name agentbox -f "$XR_RUNTIME_FILE")
GUI_TOOLS_FILE="${SCRIPT_DIR}/docker-compose.gui-tools.yml"
GUI_TOOLS_COMPOSE_ARGS=(--project-name agentbox -f "$GUI_TOOLS_FILE")
OPENMED_FILE="${SCRIPT_DIR}/docker-compose.openmed.yml"
OPENMED_COMPOSE_ARGS=(--project-name agentbox -f "$OPENMED_FILE")
# Voice + AoE operator console sidecar (its own lifecycle, like browsercontainer).
# The caddy console lives in docker-compose.voice.yml; the Kyutai Unmute speech
# stack is an external build context (voice-stack/unmute clone) layered via
# voice/unmute-override.yml. VOICE_UNMUTE_DIR is the container path to that clone
# (bind SOURCES inside the compose resolve on the HOST — see voice/README.md).
VOICE_FILE="${SCRIPT_DIR}/docker-compose.voice.yml"
VOICE_OVERRIDE_FILE="${SCRIPT_DIR}/voice/unmute-override.yml"
VOICE_CONSOLE_DIR="${SCRIPT_DIR}/voice/console"
VOICE_UNMUTE_DIR="${VOICE_UNMUTE_DIR:-$(dirname "$SCRIPT_DIR")/voice-stack/unmute}"
# HOST path mapping to the container's ~/workspace/project — compose bind SOURCES
# resolve on the host docker daemon, so they must be host paths. The product config
# (docker-compose.voice.yml / voice/unmute-override.yml) references VOICE_HOST_ROOT
# and fails fast if unset; this operator-runtime script supplies the deployment
# default. Override VOICE_HOST_ROOT in the environment if your checkout differs.
VOICE_HOST_ROOT="${VOICE_HOST_ROOT:-/mnt/mldata/githubs/AR-AI-Knowledge-Graph}"
export VOICE_HOST_ROOT
# EXPERIMENTAL, GATED OFF: Android (redroid) sidecar — a genuine Play client.
# The compose service is behind the `android` profile and cmd_android additionally
# requires AGENTBOX_ENABLE_ANDROID=1. See docs/user/android.md.
ANDROID_FILE="${SCRIPT_DIR}/docker-compose.android.yml"
ANDROID_COMPOSE_ARGS=(--project-name agentbox -f "$ANDROID_FILE" --profile android)
# Standard ports — MAD has been deprecated; no port remap needed.
# All services bind to their canonical ports inside the container; the
# operator's docker-compose.override.yml may further restrict by adding
# a `127.0.0.1:` prefix to the published side.
MGMT_PORT=9090
READY_URL="http://localhost:${MGMT_PORT}/ready"
LIVE_URL="http://localhost:${MGMT_PORT}/livez"
HEALTH_URL="http://localhost:${MGMT_PORT}/health"

# Always run docker compose from the script dir so the relative seccomp
# profile path (./config/seccomp-agentbox.json) resolves correctly.
cd "$SCRIPT_DIR"

# ---------------------------------------------------------------------------
# BRIDGE_TOKEN — single source of truth (security audit Finding 2)
# ---------------------------------------------------------------------------
# The tab0-bridge authenticates every write surface with BRIDGE_TOKEN. It must
# exist in .env BEFORE the agentbox container starts, because compose loads .env
# as env_file -> PID-1 -> supervisord -> the supervised [program:tab0-bridge]
# inherits it. `voice up` reads the SAME .env so the Unmute backend
# (KYUTAI_LLM_API_KEY) and the console break-glass bearer
# (NIP98_PROXY_ALLOW_BEARER) present the matching token — no more silent 401s.
ENV_FILE="${SCRIPT_DIR}/.env"

_gen_token() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

# Read BRIDGE_TOKEN straight from .env — the AUTHORITATIVE source, because the
# agentbox container loads .env as its compose env_file (a shell-exported
# BRIDGE_TOKEN never reaches the container). Prints the value or nothing.
_bridge_token_from_file() {
    [[ -f "$ENV_FILE" ]] || return 0
    local line
    line=$(grep -E '^[[:space:]]*BRIDGE_TOKEN[[:space:]]*=' "$ENV_FILE" 2>/dev/null | tail -1)
    [[ -n "$line" ]] || return 0
    local val="${line#*=}"
    val="${val%%#*}"                        # drop trailing inline comment
    val="${val#"${val%%[![:space:]]*}"}"    # ltrim
    val="${val%"${val##*[![:space:]]}"}"    # rtrim
    val="${val%\"}"; val="${val#\"}"         # strip surrounding double quotes
    val="${val%\'}"; val="${val#\'}"         # strip surrounding single quotes
    printf '%s' "$val"
}

# Resolve BRIDGE_TOKEN for read-only consumers (voice up): .env first (what the
# running container actually enforces), ambient env only as a courtesy fallback.
_read_bridge_token() {
    local val
    val=$(_bridge_token_from_file)
    if [[ -n "$val" ]]; then
        printf '%s' "$val"
        return 0
    fi
    [[ -n "${BRIDGE_TOKEN:-}" ]] && printf '%s' "$BRIDGE_TOKEN"
    return 0
}

# Ensure .env carries a non-empty BRIDGE_TOKEN, generating and persisting one on
# first use. .env is authoritative, so an already-persisted value always wins;
# otherwise adopt an ambient BRIDGE_TOKEN (if the operator set one) or generate,
# and write it into .env so the container inherits it. Exports for this process.
_ensure_bridge_token() {
    local tok
    tok=$(_bridge_token_from_file)
    if [[ -n "$tok" ]]; then
        export BRIDGE_TOKEN="$tok"
        return 0
    fi
    tok="${BRIDGE_TOKEN:-}"
    [[ -n "$tok" ]] || tok=$(_gen_token)
    if [[ -z "$tok" ]]; then
        echo -e "${RED}Could not generate BRIDGE_TOKEN (no openssl or /dev/urandom).${NC}" >&2
        return 1
    fi
    if ! touch "$ENV_FILE" 2>/dev/null; then
        echo -e "${RED}Cannot write ${ENV_FILE} to persist BRIDGE_TOKEN.${NC}" >&2
        return 1
    fi
    if grep -qE '^[[:space:]]*BRIDGE_TOKEN[[:space:]]*=' "$ENV_FILE" 2>/dev/null; then
        local tmp="${ENV_FILE}.tmp.$$"
        grep -vE '^[[:space:]]*BRIDGE_TOKEN[[:space:]]*=' "$ENV_FILE" > "$tmp" 2>/dev/null || true
        printf 'BRIDGE_TOKEN=%s\n' "$tok" >> "$tmp"
        mv "$tmp" "$ENV_FILE"
    else
        printf '\n# tab0-bridge shared bearer — auto-generated (security audit Finding 2).\n# Single source of truth: the container bridge inherits it via compose env_file;\n# `voice up` reads it for KYUTAI_LLM_API_KEY + NIP98_PROXY_ALLOW_BEARER.\nBRIDGE_TOKEN=%s\n' "$tok" >> "$ENV_FILE"
    fi
    chmod 600 "$ENV_FILE" 2>/dev/null || true
    export BRIDGE_TOKEN="$tok"
    echo -e "${GREEN}Persisted BRIDGE_TOKEN to .env (shared tab0-bridge bearer).${NC}"
    return 0
}

cmd_up() {
    local do_build=0
    local do_registry=0
    local wait_live=0
    while [[ $# -gt 0 ]]; do
        case $1 in
            --build)     do_build=1;    shift ;;
            --registry)  do_registry=1; shift ;;
            --wait-live) wait_live=1;   shift ;;
            -h|--help)  echo "Usage: $0 up [--build | --registry] [--wait-live]"; return 0 ;;
            *) echo -e "${RED}Unknown option: $1${NC}"; exit 1 ;;
        esac
    done

    # Mutual exclusion
    if [[ "$do_build" -eq 1 && "$do_registry" -eq 1 ]]; then
        echo -e "${RED}ERROR: --build and --registry are mutually exclusive.${NC}"
        echo "Use --build to compile a local image, or --registry to use a pre-pulled registry image."
        exit 1
    fi

    if [[ "$do_build" -eq 1 ]]; then
        echo -e "${CYAN}Building Nix runtime image...${NC}"
        nix build .#runtime
        echo -e "${CYAN}Loading image into Docker...${NC}"
        # nix2container output is an OCI manifest JSON, not a tarball;
        # copyToDockerDaemon uses skopeo to load directly into the daemon.
        nix run .#runtime.copyToDockerDaemon
        # Unset any pre-existing override so compose uses the default local tag
        unset AGENTBOX_IMAGE_REF
    fi

    if [[ "$do_registry" -eq 1 ]]; then
        if [[ -z "${AGENTBOX_IMAGE_REF:-}" ]]; then
            echo -e "${RED}ERROR: --registry requires AGENTBOX_IMAGE_REF to be set in the environment.${NC}"
            echo "Example: export AGENTBOX_IMAGE_REF=ghcr.io/dreamlab-ai/agentbox:latest"
            exit 1
        fi
    fi

    # Resolve the image reference that compose will actually use, mirroring the
    # shell-expansion default in the generated docker-compose.yml.
    local system_tag
    system_tag=$(docker version --format '{{.Server.Os}}/{{.Server.Arch}}' 2>/dev/null \
                 | sed 's|linux/amd64|x86_64-linux|;s|linux/arm64|aarch64-linux|' \
                 || echo "runtime")
    local resolved_ref="${AGENTBOX_IMAGE_REF:-agentbox:runtime-${system_tag}}"
    echo -e "${CYAN}using image: ${resolved_ref}${NC}"

    # Ensure the external network exists (standalone-first: no pre-existing
    # host deployment required). Silently succeeds if already present.
    if ! docker network inspect visionclaw_network >/dev/null 2>&1; then
        echo -e "${CYAN}Creating external network visionclaw_network...${NC}"
        docker network create visionclaw_network
    fi

    # Adopt an orphaned ruvector-postgres container if one exists outside
    # compose management (e.g. started by hand with `docker run` during the
    # 2026-06-09 outage). Compose refuses to start a service whose
    # container_name is taken by a foreign container. Removal is safe: all
    # data lives on the named volume (ruvector_postgres_data_v2), which the
    # compose service re-mounts.
    if docker inspect ruvector-postgres >/dev/null 2>&1; then
        local rv_project
        rv_project=$(docker inspect ruvector-postgres \
            --format '{{index .Config.Labels "com.docker.compose.project"}}' 2>/dev/null || true)
        if [[ -z "$rv_project" ]]; then
            echo -e "${YELLOW}Removing non-compose ruvector-postgres container (data persists on its named volume)...${NC}"
            docker rm -f ruvector-postgres >/dev/null
        fi
    fi

    # Finding 2: mint/persist the shared tab0-bridge bearer into .env BEFORE the
    # container reads .env as env_file, so the supervised bridge starts
    # authenticated on its 0.0.0.0 bind. Best-effort — a failure here only
    # disables the voice/nostr bridge, not the core stack.
    _ensure_bridge_token || echo -e "${YELLOW}Continuing without BRIDGE_TOKEN — tab0-bridge will not start on a non-loopback bind.${NC}"

    echo -e "${CYAN}Starting Docker stack...${NC}"
    docker compose "${COMPOSE_ARGS[@]}" up -d

    if [[ "$wait_live" -eq 1 ]]; then
        # Quick liveness-only wait — process alive and event loop responsive
        local live_deadline=$(( $(date +%s) + 30 ))
        local live_ok=0
        echo -e "${CYAN}Waiting for liveness at ${LIVE_URL}...${NC}"
        while [[ $(date +%s) -lt $live_deadline ]]; do
            if curl -sf "${LIVE_URL}" >/dev/null 2>&1; then
                live_ok=1
                break
            fi
            sleep 2
        done
        if [[ "$live_ok" -eq 0 ]]; then
            echo -e "${RED}ERROR: Liveness check timed out after 30s (${LIVE_URL}).${NC}"
            echo "Check logs with: $0 logs"
            exit 1
        fi
        echo -e "${GREEN}Process is live.${NC}"
        return 0
    fi

    # Full readiness wait — up to 120s (bootstrap + adapter connect can take time)
    local deadline=$(( $(date +%s) + 120 ))
    local ready=0
    echo -e "${CYAN}Waiting for /ready at ${READY_URL}...${NC}"
    while [[ $(date +%s) -lt $deadline ]]; do
        if curl -sf "${READY_URL}" >/dev/null 2>&1; then
            ready=1
            break
        fi
        sleep 2
    done

    if [[ "$ready" -eq 0 ]]; then
        echo -e "${RED}ERROR: Readiness check timed out after 120s (${READY_URL}).${NC}"
        echo "Check logs with: $0 logs"
        exit 1
    fi

    echo ""
    echo -e "${GREEN}Stack is up and ready.${NC}"
    echo -e "  ${GREEN}Management API :${NC} http://localhost:9090"
    echo -e "  ${GREEN}Prometheus     :${NC} http://localhost:9091/metrics"
    echo -e "  ${GREEN}Logs           :${NC} $0 logs"
    echo -e "  ${GREEN}Shell          :${NC} $0 shell"
}

cmd_down() {
    local remove_volumes=0
    while [[ $# -gt 0 ]]; do
        case $1 in
            --volumes) remove_volumes=1; shift ;;
            -h|--help) echo "Usage: $0 down [--volumes]"; return 0 ;;
            *) echo -e "${RED}Unknown option: $1${NC}"; exit 1 ;;
        esac
    done

    if [[ "$remove_volumes" -eq 1 ]]; then
        echo -e "${YELLOW}WARNING: --volumes will permanently delete all named volumes.${NC}"
        printf "Proceed? [y/N] "
        read -r answer
        case "$answer" in
            y|Y|yes|YES) ;;
            *) echo "Aborted."; exit 0 ;;
        esac
    fi

    local flags=""
    [[ "$remove_volumes" -eq 1 ]] && flags="-v"

    echo -e "${CYAN}Stopping Docker stack...${NC}"
    # shellcheck disable=SC2086
    docker compose "${COMPOSE_ARGS[@]}" down $flags

    echo ""
    echo -e "${GREEN}Stack stopped.${NC}"
    [[ "$remove_volumes" -eq 1 ]] && echo -e "  ${YELLOW}Named volumes removed.${NC}"
    return 0
}

cmd_build() {
    local variant="runtime"
    while [[ $# -gt 0 ]]; do
        case $1 in
            --variant) variant="$2"; shift 2 ;;
            -h|--help) echo "Usage: $0 build [--variant runtime|desktop|full]"; return 0 ;;
            *) echo -e "${RED}Unknown option: $1${NC}"; exit 1 ;;
        esac
    done

    case "$variant" in
        runtime|desktop|full) ;;
        *) echo -e "${RED}Unknown variant: ${variant}. Use runtime, desktop, or full.${NC}"; exit 1 ;;
    esac

    echo -e "${CYAN}Building Nix image variant: ${variant}...${NC}"
    nix build ".#${variant}"

    local result_path
    result_path=$(readlink -f result 2>/dev/null || echo "./result")

    echo ""
    echo -e "${GREEN}Build complete.${NC}"
    echo -e "  Variant : ${variant}"
    echo -e "  Result  : ${result_path}"
    echo ""
    echo "To load into Docker:"
    echo "  nix run .#runtime.copyToDockerDaemon"
    echo "Or use: $0 up --build"
}

cmd_update() {
    # Bump all dependencies: flake inputs (nixpkgs, rust-overlay, …) and npm
    # CLI package versions in flake.nix, then resolve Nix hashes.
    # This is intentionally a MANUAL step — auto-bumping on every build breaks
    # Nix reproducibility (same flake = same image). Call this from the
    # onboarding wizard or explicitly before a release rebuild.
    #
    # Usage:
    #   ./agentbox.sh update                — full update: flake inputs + npm CLIs + hashes
    #   ./agentbox.sh update --check        — report available updates, do not patch
    #   ./agentbox.sh update --npm-only     — skip flake input update, only bump npm CLIs
    #   ./agentbox.sh update --flake-only   — only update flake inputs (nixpkgs etc.)

    local check_only=0
    local skip_flake=0
    local skip_npm=0
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --check)      check_only=1 ;;
            --npm-only)   skip_flake=1 ;;
            --flake-only) skip_npm=1 ;;
            -h|--help)    echo "Usage: $0 update [--check] [--npm-only] [--flake-only]"; return 0 ;;
        esac
        shift
    done

    echo -e "${CYAN}Checking upstream releases...${NC}"
    bash "${SCRIPT_DIR}/scripts/check-upstream-releases.sh" || true

    if [[ "$check_only" -eq 1 ]]; then
        echo -e "${YELLOW}[--check mode] no patches applied.${NC}"
        return 0
    fi

    if ! command -v nix >/dev/null 2>&1; then
        echo -e "${RED}nix not found — cannot resolve hashes.${NC}"
        return 1
    fi

    # ── Phase 1: flake inputs (nixpkgs, rust-overlay, nix2container, flake-utils) ──
    if [[ "$skip_flake" -eq 0 ]]; then
        echo ""
        echo -e "${CYAN}Updating flake inputs (nixpkgs, rust-overlay, nix2container, flake-utils)...${NC}"
        if nix flake update --flake "${SCRIPT_DIR}"; then
            echo -e "${GREEN}  flake.lock updated.${NC}"
        else
            echo -e "${RED}  nix flake update failed — continuing with npm CLI bumps.${NC}"
        fi
    fi

    if [[ "$skip_npm" -eq 1 ]]; then
        echo ""
        echo -e "${GREEN}Done (flake inputs only). Review flake.lock and commit.${NC}"
        echo "  git diff flake.lock"
        echo "  git add flake.lock && git commit -m 'chore(deps): update flake inputs'"
        return 0
    fi

    # ── Phase 2: npm CLI version bumps ──
    echo ""
    echo -e "${CYAN}Bumping npm CLI versions in flake.nix...${NC}"
    bash "${SCRIPT_DIR}/scripts/bump-npm-cli-versions.sh"

    # ── Phase 3: hash resolution ──
    if grep -q 'lib\.fakeHash' "${SCRIPT_DIR}/flake.nix" 2>/dev/null; then
        echo ""
        echo -e "${CYAN}Resolving npm CLI hashes (iterative build + patch)...${NC}"
        echo -e "  This may take several minutes for first-time fetches."
        echo ""
        NIXPKGS_ALLOW_INSECURE=1 bash "${SCRIPT_DIR}/scripts/prefetch-hashes.sh" --cli
    else
        echo -e "${GREEN}All hashes already resolved — no prefetch needed.${NC}"
    fi

    echo ""
    echo -e "${GREEN}Done. Review changes and commit before next build.${NC}"
    echo "  git diff flake.lock flake.nix lib/"
    echo "  git add flake.lock flake.nix lib/ && git commit -m 'chore(deps): update flake inputs + bump npm CLIs'"
}

cmd_ruvector() {
    # Careful, gated lifecycle management for the ruvector-postgres sidecar.
    # The image pin lives in agentbox.toml [integrations.ruvector_external]
    # (flake composeText reads it) mirrored into docker-compose.yml; the
    # engine rehearses every update on a pg_basebackup snapshot before the
    # production volume (2M+ memory_entries) is touched, and records state
    # so `rollback` can restore the previous image + datadir.
    exec bash "${SCRIPT_DIR}/scripts/ruvector-sidecar-update.sh" "$@"
}

cmd_ruvnet_brain() {
    # RuvNet Brain corpus playbook (see [skills.ruvnet_brain] in agentbox.toml).
    # The corpus lives in the ruvector-postgres sidecar (namespace ruvnet-kb);
    # ingest reconciles it against the latest upstream GitHub release. The
    # container env carries RUVNET_BRAIN_* config; only the conninfo needs
    # container-side password resolution (same form the MCP registration uses).
    local subcmd="${1:-status}"
    shift 2>/dev/null || true
    # RUVNET_BRAIN_STAGING must sit on the workspace volume: the baked image's
    # script defaults to read-only /var/lib, and the repo default ~/.cache is a
    # 256M tmpfs in this deployment — both too small/unwritable for the ~512MB
    # corpus zip + extraction. The staging is transient; the DB is the destination.
    local ingest_env='RUVECTOR_PG_CONNINFO="host=ruvector-postgres port=5432 dbname=ruvector user=ruvector password=${RUVECTOR_PG_PASSWORD:-ruvector}" RUVNET_BRAIN_STAGING=/home/devuser/workspace/.tmp/ruvnet-brain-staging'
    case "$subcmd" in
        ingest)
            echo -e "${CYAN}Reconciling RuvNet KB corpus (this embeds via Xinference; new corpus ≈ minutes)...${NC}"
            docker exec --user 1000 agentbox bash -c \
                "${ingest_env} node /opt/agentbox/scripts/ruvnet-brain-ingest.mjs $*"
            ;;
        status)
            docker exec --user 1000 agentbox bash -c \
                "${ingest_env} node /opt/agentbox/scripts/ruvnet-brain-ingest.mjs --status"
            ;;
        logs)
            docker exec agentbox tail -n 100 -f /var/log/ruvnet-brain-ingest.log
            ;;
        *)
            echo "Usage: $0 ruvnet-brain <ingest [--force]|status|logs>"
            exit 1
            ;;
    esac
}

cmd_rebuild() {
    if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
        echo "Usage: $0 rebuild [--no-cleanup]"
        echo "Equivalent to: down + build --variant runtime + up --build + cleanup"
        echo "Cleanup also reaps runaway/stale Rust target caches (AGENTBOX_REAP_CARGO=0 to skip;"
        echo "tune via AGENTBOX_CARGO_REAP_MAX_GB / _STALE_DAYS / _DRYRUN)."
        return 0
    fi

    local skip_cleanup=0
    [[ "${1:-}" == "--no-cleanup" ]] && skip_cleanup=1

    echo -e "${CYAN}=== Rebuild: stopping stack ===${NC}"
    cmd_down

    echo -e "${CYAN}=== Rebuild: building runtime image ===${NC}"
    cmd_build --variant runtime

    echo -e "${CYAN}=== Rebuild: starting stack ===${NC}"
    cmd_up --build

    if [[ "$skip_cleanup" -eq 0 ]]; then
        echo -e "${CYAN}=== Rebuild: cleaning up old images + Nix store ===${NC}"
        bash "${SCRIPT_DIR}/scripts/post-deploy-cleanup.sh" || true
    fi
}

cmd_logs() {
    local service="${1:-}"
    if [[ "$service" == "-h" || "$service" == "--help" ]]; then
        echo "Usage: $0 logs [service]"
        return 0
    fi

    if [[ -z "$service" ]]; then
        docker compose "${COMPOSE_ARGS[@]}" logs -f --tail 100
        return
    fi

    # Try supervisorctl inside the running container first
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -q '^agentbox$'; then
        echo -e "${CYAN}Following supervisorctl log for: ${service}${NC}"
        docker exec agentbox supervisorctl tail -f "${service}" 2>/dev/null && return
        echo -e "${YELLOW}supervisorctl unavailable for '${service}', falling back to compose logs...${NC}"
    fi

    docker compose "${COMPOSE_ARGS[@]}" logs -f "${service}"
}

cmd_shell() {
    local profile="${1:-}"
    if [[ "$profile" == "-h" || "$profile" == "--help" ]]; then
        echo "Usage: $0 shell [profile]"
        return 0
    fi

    if [[ -z "$profile" ]]; then
        docker exec -it --user 1000 agentbox bash -c \
            'bash /opt/agentbox/config/tmux-autostart.sh 2>/dev/null; exec tmux attach -t agentbox 2>/dev/null || exec fish'
        return
    fi

    # Fall back to fish in the profile directory as devuser
    docker exec -it --user 1000 agentbox bash -c "cd /workspace/profiles/${profile} && exec fish"
}

cmd_health() {
    local as_json=0
    while [[ $# -gt 0 ]]; do
        case $1 in
            --json) as_json=1; shift ;;
            -h|--help) echo "Usage: $0 health [--json]"; return 0 ;;
            *) echo -e "${RED}Unknown option: $1${NC}"; exit 1 ;;
        esac
    done

    local response
    response=$(curl -sf "${HEALTH_URL}" 2>/dev/null) || {
        echo -e "${RED}ERROR: Could not reach ${HEALTH_URL}${NC}"
        echo "Is the stack running? Try: $0 up"
        exit 1
    }

    if [[ "$as_json" -eq 1 ]]; then
        printf '%s\n' "$response"
        exit 0
    fi

    # Pretty-print; fall back gracefully if jq is absent
    if command -v jq >/dev/null 2>&1; then
        local degraded
        degraded=$(printf '%s' "$response" | jq -r '
            .services // {} | to_entries[] |
            select(.value.status == "degraded" or .value.status == "failed") |
            .key
        ' 2>/dev/null || true)

        echo -e "${CYAN}Agentbox service health${NC}"
        printf '%s' "$response" | jq -r '
            .adapters // {} | to_entries[] |
            "  adapter/\(.key): \(.value)"
        ' 2>/dev/null | while IFS= read -r line; do
            if printf '%s' "$line" | grep -qE '(degraded|failed)'; then
                echo -e "${RED}${line}${NC}"
            else
                echo -e "${GREEN}${line}${NC}"
            fi
        done

        if [[ -n "$degraded" ]]; then
            echo ""
            echo -e "${RED}Degraded/failed services: ${degraded}${NC}"
        fi

        # Show observability metrics endpoint from /v1/meta
        local meta_response metrics_endpoint
        meta_response=$(curl -sf "http://localhost:9090/v1/meta" 2>/dev/null) || true
        if [[ -n "$meta_response" ]]; then
            metrics_endpoint=$(printf '%s' "$meta_response" | jq -r '.observability.metrics_endpoint // empty' 2>/dev/null || true)
            if [[ -n "$metrics_endpoint" ]]; then
                echo ""
                echo -e "${CYAN}Metrics endpoint: ${metrics_endpoint}${NC}"
                # Print first 5 non-comment lines from the metrics endpoint
                local metrics_out
                metrics_out=$(curl -sf "${metrics_endpoint}" 2>/dev/null | grep -v '^#' | head -5 || true)
                if [[ -n "$metrics_out" ]]; then
                    echo -e "${YELLOW}Sample metrics (first 5 non-comment lines):${NC}"
                    while IFS= read -r mline; do
                        echo "  ${mline}"
                    done <<< "$metrics_out"
                fi
            fi
        fi

        if [[ -n "$degraded" ]]; then
            exit 1
        fi
    else
        echo -e "${YELLOW}Note: jq not found; showing raw response.${NC}"
        printf '%s\n' "$response"
    fi
}

# ---------------------------------------------------------------------------
# android (redroid) sidecar lifecycle — EXPERIMENTAL, GATED OFF
# ---------------------------------------------------------------------------
# A genuine Play-certifiable Android 13 (x86_64) on the host kernel via binder.
# Purpose: be a real Google Play client for app extraction (incl. paid apps that
# refuse synthetic clients like apkeep/gpapi). Drive headlessly with
# `docker exec ... screencap|input`. Full playbook:
#   docs/user/android.md
# Two guards: compose `--profile android` (in ANDROID_COMPOSE_ARGS) AND the
# AGENTBOX_ENABLE_ANDROID=1 env check below.

cmd_android() {
    local subcmd="${1:-help}"
    shift 2>/dev/null || true
    local NAME="agentbox-android"

    # GUARD 2: refuse mutating actions unless explicitly enabled.
    case "$subcmd" in
        up|rebuild)
            if [[ "${AGENTBOX_ENABLE_ANDROID:-0}" != "1" ]]; then
                echo -e "${RED}android sidecar is gated off.${NC}"
                echo "It runs a privileged Android container holding a live Google session."
                echo "To enable for this invocation:"
                echo -e "  ${GREEN}AGENTBOX_ENABLE_ANDROID=1 $0 android up${NC}"
                echo "Prerequisites & sign-in playbook: docs/user/android.md"
                exit 1
            fi
            # Preflight: binder must be exposed by the host kernel.
            if ! grep -qw binder /proc/filesystems 2>/dev/null; then
                echo -e "${RED}Host kernel does not expose binder (needed by redroid).${NC}"
                echo "Load it on the host: sudo modprobe binder_linux devices=\"binder,hwbinder,vndbinder\""
                exit 1
            fi
            ;;
    esac

    case "$subcmd" in
        up)
            if ! docker image inspect "${ANDROID_IMAGE:-redroid/redroid:13-mtg}" >/dev/null 2>&1; then
                echo -e "${RED}GApps image ${ANDROID_IMAGE:-redroid/redroid:13-mtg} not found.${NC}"
                echo "Build it once with redroid-script (see the playbook), then retry."
                exit 1
            fi
            echo -e "${CYAN}Starting android (redroid) sidecar...${NC}"
            docker compose "${ANDROID_COMPOSE_ARGS[@]}" up -d
            echo -e "${CYAN}Waiting for Android boot (sys.boot_completed)...${NC}"
            local deadline=$(( $(date +%s) + 180 ))
            while [[ $(date +%s) -lt $deadline ]]; do
                [[ "$(docker exec "$NAME" getprop sys.boot_completed 2>/dev/null | tr -d '\r')" == "1" ]] && {
                    echo -e "${GREEN}Android booted.${NC} ABI: $(docker exec "$NAME" getprop ro.product.cpu.abilist 2>/dev/null)"
                    echo -e "  ${GREEN}adb   :${NC} 127.0.0.1:5555 (loopback only)"
                    echo -e "  ${GREEN}drive :${NC} docker exec $NAME screencap -p >f.png ; docker exec $NAME input tap X Y"
                    echo -e "  ${GREEN}next  :${NC} $0 android id   # GSF ID to certify at google.com/android/uncertified"
                    return 0
                }
                sleep 5
            done
            echo -e "${RED}Boot timed out. Check: $0 android logs${NC}"; exit 1
            ;;
        down)
            echo -e "${CYAN}Stopping android sidecar...${NC}"
            docker compose "${ANDROID_COMPOSE_ARGS[@]}" down
            echo -e "${GREEN}Stopped. (data volume kept; 'docker volume rm agentbox_android-data' to wipe)${NC}"
            ;;
        logs)   docker compose "${ANDROID_COMPOSE_ARGS[@]}" logs -f --tail 100 ;;
        status) docker compose "${ANDROID_COMPOSE_ARGS[@]}" ps ;;
        rebuild)
            docker compose "${ANDROID_COMPOSE_ARGS[@]}" down
            cmd_android up
            ;;
        shell)  docker exec -it "$NAME" sh ;;
        id)
            # GSF device id for Play-Protect certification (register at
            # https://www.google.com/android/uncertified). sqlite3 in-image can
            # crash, so read the db out and parse on the host side.
            docker cp "$NAME:/data/data/com.google.android.gsf/databases/gservices.db" /tmp/gservices.db 2>/dev/null \
              && python3 -c "import sqlite3;print('GSF android_id:',dict(sqlite3.connect('/tmp/gservices.db').execute('select name,value from main').fetchall()).get('android_id'))" \
              || echo -e "${RED}GMS not checked in yet — let it run a minute after first boot.${NC}"
            ;;
        screencap)
            local dest="${1:-android-frame.png}"
            docker exec "$NAME" screencap -p > "$dest" 2>/dev/null && echo -e "${GREEN}saved ${dest}${NC}"
            ;;
        help|*)
            cat <<AND_HELP
${CYAN}Android (redroid) sidecar — EXPERIMENTAL, gated off${NC}

A genuine, Play-certifiable Android 13 (x86_64) for use as a real Google Play
client (app extraction, incl. paid apps that reject synthetic clients).

Usage: AGENTBOX_ENABLE_ANDROID=1 $0 android <command>

  up          Start the sidecar and wait for boot (gated: needs the env flag)
  down        Stop it (keeps the /data volume)
  logs        Follow container logs
  status      docker compose ps
  rebuild     down + up
  shell       sh inside the Android container
  id          Print GSF device id to register at google.com/android/uncertified
  screencap [file]  Grab the framebuffer (default android-frame.png)

Drive the UI headlessly:
  docker exec agentbox-android screencap -p > f.png
  docker exec agentbox-android input tap <x> <y>
  docker exec agentbox-android input text 'hello'

Full sign-in + extraction playbook: docs/user/android.md
AND_HELP
            ;;
    esac
}

# ---------------------------------------------------------------------------
# browsercontainer lifecycle
# ---------------------------------------------------------------------------

cmd_browsercontainer() {
    local subcmd="${1:-help}"
    shift 2>/dev/null || true

    case "$subcmd" in
        up)
            echo -e "${CYAN}Building and starting browsercontainer...${NC}"
            docker compose "${SIDECAR_COMPOSE_ARGS[@]}" up -d --build
            local deadline=$(( $(date +%s) + 60 ))
            local ready=0
            echo -e "${CYAN}Waiting for browsercontainer health...${NC}"
            while [[ $(date +%s) -lt $deadline ]]; do
                if curl -sf http://localhost:8931/health >/dev/null 2>&1; then
                    ready=1
                    break
                fi
                sleep 2
            done
            if [[ "$ready" -eq 0 ]]; then
                echo -e "${RED}Health check timed out after 60s.${NC}"
                echo "Check logs: $0 browsercontainer logs"
                exit 1
            fi
            echo -e "${GREEN}Browser container is up.${NC}"
            echo -e "  ${GREEN}MCP SSE :${NC} http://localhost:8931/sse"
            echo -e "  ${GREEN}VNC     :${NC} vnc://localhost:5903"
            echo -e "  ${GREEN}Health  :${NC} http://localhost:8931/health"
            ;;
        down)
            echo -e "${CYAN}Stopping browsercontainer...${NC}"
            docker compose "${SIDECAR_COMPOSE_ARGS[@]}" down
            echo -e "${GREEN}Browser container stopped.${NC}"
            ;;
        logs)
            docker compose "${SIDECAR_COMPOSE_ARGS[@]}" logs -f --tail 100
            ;;
        health)
            local response
            response=$(curl -sf http://localhost:8931/health 2>/dev/null) || {
                echo -e "${RED}browsercontainer not responding at http://localhost:8931/health${NC}"
                exit 1
            }
            echo -e "${GREEN}browsercontainer healthy:${NC} ${response}"
            ;;
        status)
            docker compose "${SIDECAR_COMPOSE_ARGS[@]}" ps
            ;;
        rebuild)
            echo -e "${CYAN}Rebuilding browsercontainer...${NC}"
            docker compose "${SIDECAR_COMPOSE_ARGS[@]}" down
            docker compose "${SIDECAR_COMPOSE_ARGS[@]}" build --no-cache
            cmd_browsercontainer up
            ;;
        shell)
            docker exec -it --user 1000 browsercontainer bash
            ;;
        gpu)
            echo -e "${CYAN}GPU status inside browsercontainer:${NC}"
            docker exec browsercontainer nvidia-smi 2>/dev/null || echo -e "${RED}nvidia-smi not available${NC}"
            echo ""
            echo -e "${CYAN}Vulkan status:${NC}"
            docker exec browsercontainer vulkaninfo --summary 2>/dev/null || echo -e "${RED}vulkaninfo not available${NC}"
            ;;
        cdp)
            echo -e "${CYAN}CDP connectivity:${NC}"
            local cdp_response
            cdp_response=$(curl -sf http://localhost:9222/json/version 2>/dev/null) || {
                echo -e "${RED}CDP not reachable at localhost:9222${NC}"
                echo "Is the container running? Try: $0 browsercontainer status"
                exit 1
            }
            echo -e "${GREEN}CDP version:${NC}"
            echo "$cdp_response" | python3 -m json.tool 2>/dev/null || echo "$cdp_response"
            echo ""
            echo -e "${GREEN}Open tabs:${NC}"
            curl -sf http://localhost:9222/json/list 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "(failed)"
            ;;
        help|*)
            cat <<BC_HELP
${CYAN}Browser Container — hardware-accelerated Chrome with chrome-devtools-mcp${NC}

Usage: $0 browsercontainer <command>

  ${GREEN}up${NC}        Build and start the container (waits for health)
  ${GREEN}down${NC}      Stop the container
  ${GREEN}logs${NC}      Follow container logs
  ${GREEN}health${NC}    Check MCP health endpoint
  ${GREEN}status${NC}    Show container status
  ${GREEN}rebuild${NC}   Full rebuild (down + build --no-cache + up)
  ${GREEN}shell${NC}     Open bash in the container
  ${GREEN}gpu${NC}       Check GPU and Vulkan status inside container
  ${GREEN}cdp${NC}       Check CDP connectivity and list browser tabs

Chrome with Vulkan/ANGLE hardware acceleration on GPU 2
(Quadro RTX 6000, 24GB). WebGL rendering, not WebGPU.
Agents connect via MCP SSE at http://browsercontainer:8931/sse.

Port layout:
  5903  VNC desktop (view Chrome)
  8931  MCP SSE bridge (chrome-devtools-mcp)
  9222  CDP proxy (host:9222 → socat:9223 → Chrome:9222)

CDP diagnostic: docker exec browsercontainer node /opt/browsercontainer/cdp-diagnose.js
VNC monitoring:  vnc://localhost:5903
BC_HELP
            ;;
    esac
}

# ---------------------------------------------------------------------------
# xr-runtime lifecycle (Monado OpenXR desktop runtime + Godot 4.3)
# ---------------------------------------------------------------------------

cmd_xr_runtime() {
    local subcmd="${1:-help}"
    shift 2>/dev/null || true

    case "$subcmd" in
        up)
            echo -e "${CYAN}Building and starting xr-runtime...${NC}"
            echo -e "${YELLOW}First boot compiles the gdext cdylib (~5-10 min cold); be patient.${NC}"
            docker compose "${XR_RUNTIME_COMPOSE_ARGS[@]}" up -d --build
            # No HTTP health endpoint — gate on the container's own healthcheck.
            local deadline=$(( $(date +%s) + 720 ))
            local status=""
            echo -e "${CYAN}Waiting for xr-runtime to report healthy...${NC}"
            while [[ $(date +%s) -lt $deadline ]]; do
                status=$(docker inspect --format '{{.State.Health.Status}}' xr-runtime 2>/dev/null || echo "missing")
                [[ "$status" == "healthy" ]] && break
                [[ "$status" == "missing" ]] && { echo -e "${RED}Container not found.${NC}"; exit 1; }
                sleep 5
            done
            if [[ "$status" != "healthy" ]]; then
                echo -e "${RED}Health check did not pass within 12 min (status: ${status}).${NC}"
                echo "Check logs: $0 xr-runtime logs"
                exit 1
            fi
            echo -e "${GREEN}xr-runtime is up.${NC}"
            echo -e "  ${GREEN}VNC      :${NC} vnc://localhost:5904  (watch Monado compositor + Godot stereo render)"
            echo -e "  ${GREEN}Runtime  :${NC} Monado (simulated stereo HMD, core OpenXR)"
            echo -e "  ${GREEN}Scene    :${NC} XRBoot → GraphScene (override via XR_GODOT_SCENE)"
            ;;
        down)
            echo -e "${CYAN}Stopping xr-runtime...${NC}"
            docker compose "${XR_RUNTIME_COMPOSE_ARGS[@]}" down
            echo -e "${GREEN}xr-runtime stopped.${NC}"
            ;;
        logs)
            docker compose "${XR_RUNTIME_COMPOSE_ARGS[@]}" logs -f --tail 100
            ;;
        health)
            local status
            status=$(docker inspect --format '{{.State.Health.Status}}' xr-runtime 2>/dev/null) || {
                echo -e "${RED}xr-runtime container not found. Try: $0 xr-runtime up${NC}"
                exit 1
            }
            if [[ "$status" == "healthy" ]]; then
                echo -e "${GREEN}xr-runtime healthy.${NC}"
            else
                echo -e "${YELLOW}xr-runtime status: ${status}${NC}"
                echo "Recent healthcheck output:"
                docker inspect --format '{{range .State.Health.Log}}{{.Output}}{{end}}' xr-runtime 2>/dev/null | tail -20
            fi
            ;;
        status)
            docker compose "${XR_RUNTIME_COMPOSE_ARGS[@]}" ps
            ;;
        rebuild)
            echo -e "${CYAN}Rebuilding xr-runtime...${NC}"
            docker compose "${XR_RUNTIME_COMPOSE_ARGS[@]}" down
            docker compose "${XR_RUNTIME_COMPOSE_ARGS[@]}" build --no-cache
            cmd_xr_runtime up
            ;;
        shell)
            docker exec -it --user 1000 xr-runtime bash
            ;;
        gpu)
            echo -e "${CYAN}GPU status inside xr-runtime:${NC}"
            docker exec xr-runtime nvidia-smi 2>/dev/null || echo -e "${RED}nvidia-smi not available${NC}"
            echo ""
            echo -e "${CYAN}Vulkan status:${NC}"
            docker exec xr-runtime vulkaninfo --summary 2>/dev/null || echo -e "${RED}vulkaninfo not available${NC}"
            ;;
        vnc)
            echo -e "${GREEN}Connect a VNC viewer to:${NC} vnc://localhost:5904"
            echo "Watch the Monado compositor window + Godot stereo render."
            echo "Default HMD is static (simulated). For 6DoF: set XR_INPUT_DRIVER=qwerty (experimental)."
            ;;
        help|*)
            cat <<XR_HELP
${CYAN}XR Runtime — Monado OpenXR desktop runtime + Godot 4.3 (no headset)${NC}

Usage: $0 xr-runtime <command>

  ${GREEN}up${NC}        Build and start (waits for container health; first boot ~5-10 min)
  ${GREEN}down${NC}      Stop the container
  ${GREEN}logs${NC}      Follow logs (watch gdext build + OpenXR session bring-up)
  ${GREEN}health${NC}    Show Docker health status + recent healthcheck output
  ${GREEN}status${NC}    Show container status
  ${GREEN}rebuild${NC}   Full rebuild (down + build --no-cache + up)
  ${GREEN}shell${NC}     Open bash in the container
  ${GREEN}gpu${NC}       Check GPU and Vulkan status inside container
  ${GREEN}vnc${NC}       Print the VNC address to watch the stereo render

Monado runs a simulated stereo HMD — validates core OpenXR
(session lifecycle, stereo submit, scene mount, presence WS, binary protocol).
Quest vendor extensions (passthrough/hand-tracking/foveation/anchors) are
Android-only and do NOT run here. See xr-runtime/README.md.

Port layout:
  5904  VNC (Monado compositor window + Godot stereo render)
XR_HELP
            ;;
    esac
}

cmd_setup() {
    check_ip
    echo -e "${CYAN}Running initial setup on agentbox...${NC}"

    # Copy setup script and run
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$AGENTBOX_USER@$AGENTBOX_IP" << 'SETUP_EOF'
#!/bin/bash
set -e

echo "=== Agentbox Initial Setup ==="

# Update system
sudo dnf update -y

# Install Docker
sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo systemctl enable --now docker
sudo usermod -aG docker $USER

# Install development tools
sudo dnf install -y git nodejs npm python3-pip zellij htop

# Install VNC stack
echo "Installing VNC desktop..."
sudo dnf install -y xorg-x11-server-Xvfb x11vnc openbox xterm chromium

# Install agent-browser and playwright
echo "Installing browser automation tools..."
sudo npm install -g agent-browser playwright
sudo npx playwright install chromium

# Create VNC startup script
cat > ~/start-vnc.sh << 'VNCSCRIPT'
#!/bin/bash
export DISPLAY=:1
rm -f /tmp/.X*-lock /tmp/.X11-unix/X* 2>/dev/null
Xvfb :1 -screen 0 4096x4096x24 -ac +extension GLX +render -noreset &
sleep 2
openbox &
x11vnc -display :1 -rfbport 5901 -forever -shared -nopw -xkb -localhost &
echo "VNC started on localhost:5901 (use SSH tunnel)"
VNCSCRIPT
chmod +x ~/start-vnc.sh

# Create browser startup script
cat > ~/start-browser.sh << 'BROWSERSCRIPT'
#!/bin/bash
export DISPLAY=:1
chromium --no-sandbox --remote-debugging-port=9222 \
  --user-data-dir=$HOME/.config/chromium-automation \
  --window-size=1920,1080 --disable-gpu "$@" &
echo "Browser started with CDP on port 9222"
BROWSERSCRIPT
chmod +x ~/start-browser.sh

# Open firewall ports (localhost only for VNC/CDP)
sudo firewall-cmd --permanent --add-port=22/tcp
sudo firewall-cmd --permanent --add-port=8080/tcp
sudo firewall-cmd --permanent --add-port=9090/tcp
sudo firewall-cmd --reload

# Start VNC
~/start-vnc.sh

echo "=== Setup complete! ==="
echo ""
echo "VNC: Use SSH tunnel - ssh -L 5901:localhost:5901 $USER@hostname"
echo "Browser: ~/start-browser.sh, then agent-browser open <url>"
SETUP_EOF

    echo -e "${GREEN}Setup complete!${NC}"
}

# ---------------------------------------------------------------------------
# cmd_migrate_workspace — Q43 MAD volume migration
#
# Rsyncs the legacy multi-agent-docker_workspace external volume into a
# fresh agentbox-owned named volume, then patches docker-compose.override.yml
# to point at the new volume. This is a one-shot. Idempotent: if the new
# volume already has content matching the source, rsync is a no-op.
# ---------------------------------------------------------------------------
cmd_migrate_workspace() {
    local force=0
    local target_volume="agentbox-workspace"
    local source_volume="multi-agent-docker_workspace"
    while [[ $# -gt 0 ]]; do
        case $1 in
            --force)        force=1; shift ;;
            --source)       source_volume="$2"; shift 2 ;;
            --target)       target_volume="$2"; shift 2 ;;
            -h|--help)
                cat <<'HELP_EOF'
Usage: agentbox.sh migrate-workspace [--source NAME] [--target NAME] [--force]

Rsync the legacy multi-agent-docker_workspace external volume into an
agentbox-owned named volume, then patch docker-compose.override.yml to
reference the new volume. Idempotent.

Steps performed:
  1. Verify source volume exists.
  2. Create target volume (skipped if present).
  3. Stop the agentbox container if running (so the source isn't mid-write).
  4. Run rsync inside a busybox container with both volumes mounted.
  5. Patch docker-compose.override.yml: rename mad-workspace alias and
     point it at the new volume; the bind target stays
     /home/devuser/workspace.
  6. Print next steps for the operator (review override, restart stack).

Use --force to skip the "are you sure" confirmation.
HELP_EOF
                return 0 ;;
            *) echo -e "${RED}Unknown option: $1${NC}"; exit 1 ;;
        esac
    done

    if ! docker volume inspect "$source_volume" >/dev/null 2>&1; then
        echo -e "${RED}ERROR: source volume '$source_volume' does not exist on this Docker daemon.${NC}"
        echo "If MAD never ran here there's nothing to migrate; the override's mad-workspace alias is harmless."
        exit 1
    fi

    echo -e "${CYAN}Source volume:${NC} $source_volume"
    echo -e "${CYAN}Target volume:${NC} $target_volume"
    if docker volume inspect "$target_volume" >/dev/null 2>&1; then
        echo -e "${YELLOW}Target volume already exists. Rsync will sync deltas in place.${NC}"
    fi

    if [[ "$force" -ne 1 ]]; then
        echo -e "${YELLOW}This will:${NC}"
        echo "  • Stop the agentbox container if running"
        echo "  • Rsync ~157 GB from $source_volume to $target_volume (incremental)"
        echo "  • Update docker-compose.override.yml to reference $target_volume"
        echo ""
        read -p "Proceed? [y/N] " -n 1 -r
        echo
        [[ ! $REPLY =~ ^[Yy]$ ]] && { echo "Aborted."; exit 0; }
    fi

    if docker ps --format '{{.Names}}' | grep -qx agentbox; then
        echo -e "${CYAN}Stopping agentbox container...${NC}"
        docker compose "${COMPOSE_ARGS[@]}" stop agentbox || true
    fi

    docker volume create "$target_volume" >/dev/null

    echo -e "${CYAN}Rsyncing $source_volume -> $target_volume (this may take a while)...${NC}"
    docker run --rm \
        -v "$source_volume":/src:ro \
        -v "$target_volume":/dst \
        instrumentisto/rsync-ssh:alpine \
        rsync -aHAX --info=progress2 --human-readable /src/ /dst/

    echo -e "${CYAN}Patching docker-compose.override.yml...${NC}"
    if grep -q "name: $source_volume" "$OVERRIDE_FILE"; then
        # Rewrite the external alias so the override now references the
        # new volume. The bind path /home/devuser/workspace is unchanged.
        sed -i.pre-migrate \
            -e "s|external: true|external: false|" \
            -e "s|name: $source_volume|name: $target_volume|" \
            "$OVERRIDE_FILE"
        # Also rename the local alias from mad-workspace to agentbox-workspace
        # to remove the misleading reference. Keep the bind name in sync.
        sed -i \
            -e "s|mad-workspace:|$target_volume:|g" \
            "$OVERRIDE_FILE"
        echo -e "${GREEN}Override patched. Backup at $OVERRIDE_FILE.pre-migrate${NC}"
    else
        echo -e "${YELLOW}Override doesn't reference $source_volume — skipping patch.${NC}"
    fi

    echo ""
    echo -e "${GREEN}Migration complete.${NC}"
    echo -e "${CYAN}Next steps:${NC}"
    echo "  1. Review: diff $OVERRIDE_FILE.pre-migrate $OVERRIDE_FILE"
    echo "  2. Start:  $0 up"
    echo "  3. Verify: docker exec agentbox ls /home/devuser/workspace | head"
    echo "  4. Once happy, you can `docker volume rm $source_volume` to free disk."
}

# ---------------------------------------------------------------------------
# cmd_preflight — local env + manifest validation before `up`
#
# Catches the cascade of errors that ate the last debug session by
# validating ahead of `docker compose up`:
#   • W021: any active security exception widening the surface must have
#     `[security].audit_acknowledged = true` in agentbox.toml.
#   • Override paths exist on the host (e.g. ${HOME}/.claude).
#   • Compose configs merge cleanly (no conflicting volumes/ports).
#   • Required env vars are set or have safe defaults.
# ---------------------------------------------------------------------------
cmd_preflight() {
    local errors=0

    echo -e "${CYAN}Preflight: validating compose merge...${NC}"
    if ! docker compose "${COMPOSE_ARGS[@]}" config >/dev/null 2>&1; then
        echo -e "${RED}  ✗ docker compose config failed${NC}"
        docker compose "${COMPOSE_ARGS[@]}" config 2>&1 | head -10
        errors=$((errors+1))
    else
        echo -e "${GREEN}  ✓ compose merges cleanly${NC}"
    fi

    echo -e "${CYAN}Preflight: validating Nix flake (W021 audit gate)...${NC}"
    if ! nix build .#compose --no-link 2>&1 | tail -5; then
        echo -e "${RED}  ✗ nix build .#compose failed (W021 may be blocking)${NC}"
        errors=$((errors+1))
    else
        echo -e "${GREEN}  ✓ flake evaluates; W021 satisfied${NC}"
    fi

    echo -e "${CYAN}Preflight: checking host bind targets...${NC}"
    for hostpath in "${HOME}/.claude" "${HOME}/.config/claude" "${HOME}/.codex/auth.json" "/mnt/mldata/githubs/AR-AI-Knowledge-Graph"; do
        if [[ ! -e "$hostpath" ]]; then
            echo -e "${YELLOW}  ! $hostpath does not exist — bind will create it root-owned${NC}"
        else
            echo -e "${GREEN}  ✓ $hostpath${NC}"
        fi
    done

    echo -e "${CYAN}Preflight: checking external volumes...${NC}"
    for vol in multi-agent-docker_workspace agentbox-workspace; do
        if docker volume inspect "$vol" >/dev/null 2>&1; then
            echo -e "${GREEN}  ✓ $vol exists${NC}"
        fi
    done

    if [[ "$errors" -gt 0 ]]; then
        echo -e "${RED}Preflight failed with $errors error(s).${NC}"
        return 1
    fi
    echo -e "${GREEN}Preflight passed.${NC}"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -i|--ip)
            AGENTBOX_IP="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        ssh|vnc|browser|code|api|all|status|ip|provision|setup|start-browser|backup|restore|up|down|build|rebuild|update|ruvector|ruvnet-brain|logs|shell|health|browsercontainer|gui-tools|openmed|voice|xr-runtime|android|migrate-workspace|preflight)
            CMD="$1"
            shift
            break
            ;;
        *)
            echo -e "${RED}Unknown command: $1${NC}"
            usage
            exit 1
            ;;
    esac
done

cmd_gui_tools() {
    local subcmd="${1:-help}"
    shift 2>/dev/null || true
    case "$subcmd" in
        up)
            echo -e "${CYAN}Building and starting gui-tools-service (GPU Blender + QGIS sidecar)...${NC}"
            docker compose "${GUI_TOOLS_COMPOSE_ARGS[@]}" up -d --build
            echo -e "${CYAN}Waiting for BlenderMCP health (start-period ~60s)...${NC}"
            local deadline=$(( $(date +%s) + 120 )) ready=0
            while [[ $(date +%s) -lt $deadline ]]; do
                if docker exec gui-tools-service bash /opt/gui-tools/healthcheck.sh >/dev/null 2>&1; then ready=1; break; fi
                sleep 3
            done
            if [[ "$ready" -eq 0 ]]; then
                echo -e "${RED}Health check timed out.${NC} Check logs: $0 gui-tools logs"
                exit 1
            fi
            echo -e "${GREEN}gui-tools-service is up.${NC}"
            echo -e "  ${GREEN}BlenderMCP :${NC} gui-tools-service:9876 (agentbox proxy bridges localhost:9876)"
            echo -e "  ${GREEN}QGIS MCP   :${NC} gui-tools-service:9877"
            echo -e "  ${GREEN}VNC        :${NC} vnc://localhost:5905"
            ;;
        down)
            docker compose "${GUI_TOOLS_COMPOSE_ARGS[@]}" down
            echo -e "${GREEN}gui-tools-service stopped.${NC}"
            ;;
        logs)    docker compose "${GUI_TOOLS_COMPOSE_ARGS[@]}" logs -f --tail 100 ;;
        status)  docker compose "${GUI_TOOLS_COMPOSE_ARGS[@]}" ps ;;
        health)
            docker exec gui-tools-service bash /opt/gui-tools/healthcheck.sh \
                && echo -e "${GREEN}gui-tools-service healthy${NC}" \
                || { echo -e "${RED}gui-tools-service unhealthy${NC}"; exit 1; }
            ;;
        gpu)
            echo -e "${CYAN}GPU + GL inside gui-tools-service:${NC}"
            docker exec gui-tools-service nvidia-smi -L 2>/dev/null || echo -e "${RED}nvidia-smi unavailable${NC}"
            docker exec gui-tools-service vulkaninfo --summary 2>/dev/null | head -12 || echo -e "${RED}vulkaninfo unavailable${NC}"
            ;;
        rebuild)
            docker compose "${GUI_TOOLS_COMPOSE_ARGS[@]}" down
            docker compose "${GUI_TOOLS_COMPOSE_ARGS[@]}" build --no-cache
            cmd_gui_tools up
            ;;
        shell)   docker exec -it --user 1000 gui-tools-service bash ;;
        help|*)
            cat <<GT_HELP
${CYAN}gui-tools-service — GPU-accelerated FHS sidecar for Blender + QGIS${NC}

  $0 gui-tools up        Build + start the sidecar, wait for BlenderMCP health
  $0 gui-tools down      Stop it
  $0 gui-tools logs      Follow logs
  $0 gui-tools status    Compose ps
  $0 gui-tools health    Run the in-container healthcheck
  $0 gui-tools gpu       Show GPU + Vulkan status inside the container
  $0 gui-tools rebuild   Rebuild --no-cache and restart
  $0 gui-tools shell     Shell into the container

Blender runs here (VirtualGL → GPU EGL) because nix agentbox-main cannot give it a
GPU GL context. agentbox's blender-mcp-proxy / qgis proxy bridge localhost:9876/9877
to this sidecar. See docs/user/blender.md.
GT_HELP
            ;;
    esac
}

cmd_openmed() {
    local subcmd="${1:-help}"
    shift 2>/dev/null || true
    case "$subcmd" in
        up)
            echo -e "${CYAN}Building and starting the OpenMed clinical-PHI sidecar...${NC}"
            echo -e "${YELLOW}Note: refuses to serve unless [privacy_filter.openmed] prerequisites"
            echo -e "      (license_acknowledged, onnx_runtime_present, governance_acknowledged)"
            echo -e "      are set and the model artifact verifies. Default: all false → gated off.${NC}"
            docker compose "${OPENMED_COMPOSE_ARGS[@]}" up -d --build
            echo -e "${GREEN}openmed dispatched.${NC} Check: $0 openmed health / $0 openmed logs"
            ;;
        down)    docker compose "${OPENMED_COMPOSE_ARGS[@]}" down; echo -e "${GREEN}openmed stopped.${NC}" ;;
        logs)    docker compose "${OPENMED_COMPOSE_ARGS[@]}" logs -f --tail 100 ;;
        status)  docker compose "${OPENMED_COMPOSE_ARGS[@]}" ps ;;
        health)
            docker exec openmed bash /opt/openmed/healthcheck.sh \
                && echo -e "${GREEN}openmed healthy${NC}" \
                || { echo -e "${RED}openmed unhealthy (or gated off — see logs)${NC}"; exit 1; }
            ;;
        rebuild) docker compose "${OPENMED_COMPOSE_ARGS[@]}" down; docker compose "${OPENMED_COMPOSE_ARGS[@]}" build --no-cache; cmd_openmed up ;;
        shell)   docker exec -it --user 1000 openmed bash ;;
        help|*)
            cat <<OM_HELP
${CYAN}openmed — optional, gated clinical-PHI redaction sidecar (ADR-008 local-clinical backend)${NC}

  $0 openmed up        Build + start (fail-closed on unacknowledged prerequisites)
  $0 openmed down      Stop it
  $0 openmed logs      Follow logs
  $0 openmed status    Compose ps
  $0 openmed health    In-container healthcheck
  $0 openmed rebuild   Rebuild --no-cache and restart
  $0 openmed shell     Shell into the container

Default-off. Enable via [privacy_filter.openmed] in agentbox.toml after resolving
the licence, ONNX runtime, and governance prerequisites. See docs/user/openmed.md.
OM_HELP
            ;;
    esac
}

# ---------------------------------------------------------------------------
# voice lifecycle — voice + AoE operator console (Caddy :8444/:8443) + the
# external Kyutai Unmute speech stack. Own lifecycle, like browsercontainer.
# ---------------------------------------------------------------------------

# Generate a self-signed TLS pair for the console origin if one is absent.
# Mic capture needs a secure context, so the operator origin must be HTTPS;
# the cert/key are gitignored (certs/, *.pem) and never committed.
_voice_ensure_certs() {
    local certdir="${VOICE_CONSOLE_DIR}/certs"
    if [[ -f "${certdir}/cert.pem" && -f "${certdir}/key.pem" ]]; then
        return 0
    fi
    echo -e "${CYAN}Generating self-signed TLS cert for the voice console (certs/ is gitignored)...${NC}"
    mkdir -p "$certdir"
    if ! command -v openssl >/dev/null 2>&1; then
        echo -e "${RED}openssl not found — cannot generate the console cert.${NC}"
        echo "Install openssl or drop a cert.pem/key.pem pair in ${certdir}/."
        return 1
    fi
    # SAN covers localhost + the container hostname so the cert validates from
    # the laptop/tailnet as well as loopback. 825-day validity (browser cap).
    openssl req -x509 -newkey rsa:2048 -nodes \
        -keyout "${certdir}/key.pem" -out "${certdir}/cert.pem" \
        -days 825 -subj "/CN=agentbox-voice-console" \
        -addext "subjectAltName=DNS:localhost,DNS:agentbox,DNS:voice-console,IP:127.0.0.1" \
        >/dev/null 2>&1 || {
            echo -e "${RED}Cert generation failed.${NC}"
            return 1
        }
    chmod 600 "${certdir}/key.pem"
    echo -e "${GREEN}Cert written to ${certdir}/ (self-signed; accept once in the browser).${NC}"
}

# Assemble the compose invocation. The caddy console (this repo) always
# participates; the Unmute clone's compose + our override are layered in only
# when the clone is present (26 GB external build context, not vendored).
_voice_compose_args() {
    VOICE_COMPOSE_ARGS=(--project-name agentbox-voice)
    if [[ -f "${VOICE_UNMUTE_DIR}/docker-compose.yml" ]]; then
        VOICE_COMPOSE_ARGS+=(-f "${VOICE_UNMUTE_DIR}/docker-compose.yml" -f "$VOICE_OVERRIDE_FILE")
    fi
    VOICE_COMPOSE_ARGS+=(-f "$VOICE_FILE")
}

cmd_voice() {
    local subcmd="${1:-help}"
    shift 2>/dev/null || true
    _voice_compose_args

    case "$subcmd" in
        up)
            _voice_ensure_certs || exit 1
            if [[ ! -f "${VOICE_UNMUTE_DIR}/docker-compose.yml" ]]; then
                echo -e "${YELLOW}Unmute clone not found at ${VOICE_UNMUTE_DIR}.${NC}"
                echo -e "${YELLOW}Bringing up the console only — the /embed voice strip and /api routes"
                echo -e "will 502 until the speech stack is present. Clone it with:${NC}"
                echo "  git clone https://github.com/kyutai-labs/unmute ${VOICE_UNMUTE_DIR}"
            fi
            # Finding 2: read the SAME BRIDGE_TOKEN the running bridge enforces
            # (env override, else .env) and wire it into both consumers. FAIL
            # LOUD when absent — warning-and-continuing shipped a stack whose
            # every LLM call and every break-glass request 401s.
            BRIDGE_TOKEN="$(_read_bridge_token)"
            if [[ -z "$BRIDGE_TOKEN" ]]; then
                echo -e "${RED}BRIDGE_TOKEN is unset/empty — refusing to start the voice stack.${NC}" >&2
                echo -e "${RED}The Unmute backend and console must present the SAME bearer that the${NC}" >&2
                echo -e "${RED}running tab0-bridge enforces, or every call 401s. Bring the agentbox${NC}" >&2
                echo -e "${RED}stack up first ('$0 up' generates and persists BRIDGE_TOKEN to .env),${NC}" >&2
                echo -e "${RED}or set BRIDGE_TOKEN in .env to the value the bridge is using.${NC}" >&2
                exit 1
            fi
            export BRIDGE_TOKEN
            # KYUTAI_LLM_API_KEY: the bearer the Unmute backend presents to the
            # bridge (interpolated by voice/unmute-override.yml). NIP98_PROXY_ALLOW_BEARER:
            # the console break-glass bearer the in-container nip98-proxy honours
            # — set it in .env for that proxy; exported here so the voice compose
            # and console surfaces resolve the same single secret.
            export KYUTAI_LLM_API_KEY="$BRIDGE_TOKEN"
            export NIP98_PROXY_ALLOW_BEARER="$BRIDGE_TOKEN"
            echo -e "${CYAN}Building and starting the voice console + speech stack...${NC}"
            docker compose "${VOICE_COMPOSE_ARGS[@]}" up -d --build
            local deadline=$(( $(date +%s) + 60 )) ready=0
            echo -e "${CYAN}Waiting for the console origin (https://localhost:8444)...${NC}"
            while [[ $(date +%s) -lt $deadline ]]; do
                if curl -skf https://localhost:8444/ >/dev/null 2>&1; then ready=1; break; fi
                sleep 2
            done
            if [[ "$ready" -eq 0 ]]; then
                echo -e "${RED}Console did not answer on :8444 within 60s.${NC}"
                echo "Check logs: $0 voice logs"
                exit 1
            fi
            echo -e "${GREEN}Voice console is up.${NC}"
            echo -e "  ${GREEN}Console  :${NC} https://<host>:8444  (operator cockpit — accept the self-signed cert)"
            echo -e "  ${GREEN}Debug UI :${NC} https://<host>:8443  (stock Unmute demo)"
            echo -e "  Routes: /embed (voice) · /feed+/bridge (tab0-bridge) · /aoe/* (sessions) · /approvals/* (governance)"
            ;;
        down)
            echo -e "${CYAN}Stopping the voice console + speech stack...${NC}"
            docker compose "${VOICE_COMPOSE_ARGS[@]}" down
            echo -e "${GREEN}Voice stack stopped.${NC}"
            ;;
        logs)
            docker compose "${VOICE_COMPOSE_ARGS[@]}" logs -f --tail 100
            ;;
        status)
            docker compose "${VOICE_COMPOSE_ARGS[@]}" ps
            ;;
        health)
            if curl -skf https://localhost:8444/ >/dev/null 2>&1; then
                echo -e "${GREEN}voice console healthy${NC} (https://localhost:8444)"
            else
                echo -e "${RED}voice console not responding at https://localhost:8444${NC}"
                exit 1
            fi
            # Upstreams are best-effort — report but don't fail on them.
            if curl -skf https://localhost:8444/api/v1/health >/dev/null 2>&1; then
                echo -e "${GREEN}Unmute backend reachable via /api${NC}"
            else
                echo -e "${YELLOW}Unmute backend not reachable via /api (speech stack down?)${NC}"
            fi
            ;;
        certs)
            rm -f "${VOICE_CONSOLE_DIR}/certs/cert.pem" "${VOICE_CONSOLE_DIR}/certs/key.pem"
            _voice_ensure_certs || exit 1
            echo -e "${YELLOW}Restart the console to load the new cert: $0 voice down && $0 voice up${NC}"
            ;;
        rebuild)
            _voice_ensure_certs || exit 1
            docker compose "${VOICE_COMPOSE_ARGS[@]}" down
            docker compose "${VOICE_COMPOSE_ARGS[@]}" build --no-cache
            cmd_voice up
            ;;
        shell)
            docker exec -it voice-console sh
            ;;
        help|*)
            cat <<VOICE_HELP
${CYAN}voice — voice + AoE operator console (Caddy :8444) + Kyutai Unmute speech stack${NC}

Usage: $0 voice <command>

  ${GREEN}up${NC}        Generate certs if absent, then build + start console + speech stack
  ${GREEN}down${NC}      Stop the voice stack
  ${GREEN}logs${NC}      Follow logs
  ${GREEN}status${NC}    Compose ps
  ${GREEN}health${NC}    Check the console origin (and, best-effort, the Unmute backend)
  ${GREEN}certs${NC}     Regenerate the self-signed console TLS pair (certs/ is gitignored)
  ${GREEN}rebuild${NC}   Full rebuild (down + build --no-cache + up)
  ${GREEN}shell${NC}     Shell into the caddy console container

The operator cockpit consolidates every surface same-origin on :8444:
  /embed voice strip · /feed+/bridge tab0-bridge · /aoe/* AoE sessions (via the
  NIP-98 proxy :9096) · /approvals/* governance (:9090). :8443 is the stock
  Unmute debug UI. Sign in with a NIP-98 header (window.nostr) or break-glass
  bearer. See agentbox/voice/README.md.

The Kyutai Unmute fork is an external build context (not vendored). Set its
location with VOICE_UNMUTE_DIR (default: ../voice-stack/unmute relative to the
agentbox checkout). VOICE_HOST_ROOT is the HOST path mapping to the container's
~/workspace/project — override it if your checkout is not at the default host
path. BRIDGE_TOKEN is the single shared bearer: '$0 up' generates and persists
it to .env, and 'voice up' reads that same value to authenticate the Unmute
backend (KYUTAI_LLM_API_KEY) and the console break-glass (NIP98_PROXY_ALLOW_BEARER).
'voice up' fails fast if BRIDGE_TOKEN is missing.
VOICE_HELP
            ;;
    esac
}

# Execute command
case "${CMD:-}" in
    ssh)           cmd_ssh "$@" ;;
    vnc)           cmd_vnc ;;
    browser)       cmd_browser ;;
    code)          cmd_code ;;
    api)           cmd_api ;;
    all)           cmd_all ;;
    status)        cmd_status ;;
    ip)            cmd_ip ;;
    provision)     cmd_provision "$@" ;;
    setup)         cmd_setup ;;
    start-browser) cmd_start_browser ;;
    backup)        cmd_backup "$@" ;;
    restore)       cmd_restore "$@" ;;
    up)            cmd_up "$@" ;;
    down)          cmd_down "$@" ;;
    build)         cmd_build "$@" ;;
    rebuild)       cmd_rebuild "$@" ;;
    update)        cmd_update "$@" ;;
    ruvector)      cmd_ruvector "$@" ;;
    ruvnet-brain)  cmd_ruvnet_brain "$@" ;;
    logs)              cmd_logs "$@" ;;
    shell)             cmd_shell "$@" ;;
    health)            cmd_health "$@" ;;
    browsercontainer)  cmd_browsercontainer "$@" ;;
    gui-tools)         cmd_gui_tools "$@" ;;
    openmed)           cmd_openmed "$@" ;;
    voice)             cmd_voice "$@" ;;
    xr-runtime)        cmd_xr_runtime "$@" ;;
    android)           cmd_android "$@" ;;
    migrate-workspace) cmd_migrate_workspace "$@" ;;
    preflight)         cmd_preflight "$@" ;;
    *)                 usage ;;
esac
