# lib/codex-binary.nix
#
# Nix derivation for OpenAI's Rust-native Codex CLI.
# Release: https://github.com/openai/codex/releases/tag/rust-v0.153.3
#
# Uses the official pre-built musl package archives rather than
# buildRustPackage from source — faster, deterministic, and complete.  The
# package archive is important: modern Codex releases require the sibling
# codex-code-mode-host executable and discover bundled resources relative to
# the main binary.  The legacy single-binary archive is not a complete runtime.
#
# Per-arch SHA256s are generated by `./agentbox.sh update` (or directly with
# `./scripts/bump-codex-version.sh`). Do not hand-edit the version or hashes.
#
# Supported targets: x86_64-linux, aarch64-linux (musl).
# darwin / windows are NOT supported — agentbox is Linux-container-only; users
# on other hosts pull the published multi-arch image from GHCR.

{ lib, pkgs }:

let
  codexVersion = "0.153.3";
  baseUrl = "https://github.com/openai/codex/releases/download/rust-v${codexVersion}";

  # Map agentbox's system string to OpenAI's canonical package archive.
  # musl tarballs are chosen for container portability: all bundled executables
  # are static and run in our nix2container image regardless of the base libc.
  assets = {
    "x86_64-linux" = {
      name   = "codex-package-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "47bb1fb36fb1dbd5fe1af3eb0db422ffb4c3c38d9c1762c7618a9bed46c44a63";
    };
    "aarch64-linux" = {
      name   = "codex-package-aarch64-unknown-linux-musl.tar.gz";
      sha256 = "53d4604d339cdc87f1c396aca80c2addc8e092987b1b15c5f34dcda1fa54748a";
    };
  };

  assetFor = system:
    assets.${system} or (throw ''
      lib/codex-binary.nix: no Codex release asset for system "${system}".
      Supported: ${lib.concatStringsSep ", " (builtins.attrNames assets)}.
      For darwin/windows hosts, pull the published agentbox image from GHCR
      (which is always linux/amd64 or linux/arm64) rather than building
      natively.
    '');

in

{
  # Build a codex derivation for a given system string (e.g. "x86_64-linux").
  # Invoked from flake.nix when toolchainCfg.codex is enabled.
  makeCodex = system:
    let
      asset = assetFor system;
      tarball = pkgs.fetchurl {
        url    = "${baseUrl}/${asset.name}";
        sha256 = asset.sha256;
      };
    in
    pkgs.stdenv.mkDerivation {
      pname   = "codex";
      version = codexVersion;

      src = tarball;

      # Upstream package tarballs have no wrapping directory.
      sourceRoot = ".";

      # No build required — pre-compiled binary.
      dontBuild = true;

      # Strip isn't needed (upstream already stripped).
      dontStrip = true;

      # Patchelf is unnecessary on musl. Keep every executable bit-identical to
      # the signed upstream package.
      dontPatchELF = true;

      installPhase = ''
        runHook preInstall

        # Preserve the canonical upstream package layout. Codex locates the
        # code-mode host beside itself and the sandbox/shell helpers through
        # codex-package.json relative to that executable.
        install -Dm755 bin/codex $out/bin/codex
        install -Dm755 bin/codex-code-mode-host $out/bin/codex-code-mode-host
        install -Dm755 codex-path/rg $out/codex-path/rg
        install -Dm755 codex-resources/bwrap $out/codex-resources/bwrap
        install -Dm755 codex-resources/zsh/bin/zsh $out/codex-resources/zsh/bin/zsh
        install -Dm644 codex-package.json $out/codex-package.json

        runHook postInstall
      '';

      meta = with lib; {
        description = "OpenAI's Rust-native Codex CLI and runtime helpers";
        homepage    = "https://github.com/openai/codex";
        license     = licenses.asl20;
        platforms   = builtins.attrNames assets;
        mainProgram = "codex";
      };
    };
}
