# lib/npm-services.nix
#
# Factory for local npm-based service derivations (PRD-002 §9, Phase 1).
#
# Usage:
#   npmServices = import ./lib/npm-services.nix { inherit lib pkgs; };
#   managementApiPkg = npmServices.makeNpmService {
#     name    = "management-api";
#     src     = ./management-api;
#     entry   = "server.js";
#     npmDepsHash = "<prefetched>";
#   };
#
# Output layout (what buildNpmPackage produces):
#   $out/lib/node_modules/<name>/   — full package tree including node_modules
#   $out/bin/<name>                 — wrapper generated by postInstall below
#
# Operator: compute npmDepsHash for each service by running:
#   nix run nixpkgs#prefetch-npm-deps -- <service>/package-lock.json
# or:
#   nix-prefetch-url --type sha256 file://$(nix-build -E \
#     'with import <nixpkgs> {}; fetchNpmDeps { src = ./path; hash = ""; }')
#
# The canonical command per service is printed in each fakeHash throw below.

{ lib, pkgs }:

let
  # Guard behaviour: throwing at evaluation time breaks every flake consumer
  # (nix flake check, nix build .#compose, nix eval, CI lint), not just the
  # operator who forgot to prefetch. Instead we detect the fakeHash and route
  # to a realisation-time failure so lazy evaluation consumers stay green.
  # When buildNpmPackage actually runs and fetches deps, the placeholder SRI
  # will mismatch and Nix will print both expected and got — same UX as any
  # other stale hash, with our preBuildPhase adding a pointed hint.
  fakeHashHint = name: ''
    echo "========================================" >&2
    echo "agentbox npm-service: ${name}" >&2
    echo "npmDepsHash is still lib.fakeHash. Compute the real hash:" >&2
    echo "  nix run nixpkgs#prefetch-npm-deps -- ${name}/package-lock.json" >&2
    echo "Then replace lib.fakeHash in lib/npm-services.nix." >&2
    echo "========================================" >&2
  '';

  # When fakeHash is passed, substitute a placeholder SRI so Nix can still
  # evaluate the derivation. The buildNpmPackage fetch step will fail with a
  # hash mismatch, and preBuildHook (injected below when fakeHash was used)
  # emits the operator-friendly pointer.
  resolvedHash = hash:
    if hash == lib.fakeHash
    then "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    else hash;

  isFakeHash = hash: hash == lib.fakeHash;

in

{
  # makeNpmService wraps pkgs.buildNpmPackage with the conventions required by
  # agentbox:
  #   - node_modules are baked in at build time (npmDepsHash)
  #   - a thin wrapper script is installed to $out/bin/<name> so supervisord
  #     can reference a single stable path instead of the JS entrypoint
  #   - checkPhase verifies the closure loads (catches broken imports early)
  #
  # Parameters:
  #   name              string   package name (also the bin wrapper name)
  #   src               path     path to directory containing package.json
  #   entry             string   JS entrypoint relative to the package root
  #                              e.g. "server.js" or "dist/mcp-server.js"
  #   npmDepsHash       string   sha256 from prefetch-npm-deps; use lib.fakeHash
  #                              as a placeholder and it will throw at eval time
  #   extraBuildInputs  list     extra nativeBuildInputs (e.g. nodeGyp, python3)
  #   extraEnv          attrs    additional environment variables set during build
  #   buildPhaseExtra   string   additional shell commands injected into buildPhase
  #                              (used for TypeScript compilation via tsc)
  makeNpmService = {
    name,
    src,
    entry,
    npmDepsHash,
    extraBuildInputs ? [],
    extraEnv        ? {},
    buildPhaseExtra ? "",
  }:
    let
      effectiveHash = resolvedHash npmDepsHash;
      needsHint     = isFakeHash npmDepsHash;
    in
    pkgs.buildNpmPackage ({
      pname   = name;
      version = "0.0.0";  # version is read from package.json at runtime; not
                           # semantically significant for image derivation tracking
      inherit src;

      npmDepsHash = effectiveHash;

      # Fakehash hint: emits an operator-friendly message if the build is
      # attempted without prefetching. Harmless on real hashes (no-op).
      preFetch = lib.optionalString needsHint (fakeHashHint name);

      # Do not run npm test automatically — each service has its own test
      # runner; checkPhase below does a lightweight import check instead.
      doCheck = true;

      # Extra native build inputs (e.g. node-gyp + python for native addons).
      nativeBuildInputs = [ pkgs.nodejs_20 ] ++ extraBuildInputs;

      # Extra env vars injected into the build sandbox.
      # Callers pass a string-to-string attrset; we emit KEY=VALUE pairs.
      env = extraEnv;

      # buildPhase: run any pre-packaging step (e.g. TypeScript compilation),
      # then skip 'npm run build' (not all packages define it).
      buildPhase = ''
        runHook preBuild
        ${buildPhaseExtra}
        runHook postBuild
      '';

      # checkPhase: confirm the entrypoint can be required without crashing.
      # This catches broken peer dependencies before the image layer is frozen.
      checkPhase = ''
        runHook preCheck
        node -e "require('./${entry}')" 2>/dev/null \
          || node --input-type=module <<<"import './${entry}'" 2>/dev/null \
          || echo "[check] ${name}: import check skipped (ESM-only or side-effect-free module)"
        runHook postCheck
      '';

      # postInstall: buildNpmPackage places the package at
      #   $out/lib/node_modules/<pname>/
      # We create a wrapper script at $out/bin/<name> that supervisord can use
      # as a stable reference, and a symlink into the package root for
      # path-based access from appRoot.
      postInstall = ''
        # Wrapper script for supervisord command= lines.
        mkdir -p "$out/bin"
        cat > "$out/bin/${name}" <<'WRAPPER'
        #!/usr/bin/env sh
        exec node "$(dirname "$0")/../lib/node_modules/${name}/${entry}" "$@"
        WRAPPER
        chmod +x "$out/bin/${name}"

        # Also expose the package root directory as $out/package for
        # appRoot to cp into /opt/agentbox/<name> (includes node_modules).
        ln -s "$out/lib/node_modules/${name}" "$out/package"
      '';

      meta = {
        description = "Agentbox npm service: ${name}";
        mainProgram  = name;
      };
    } // lib.optionalAttrs (extraEnv != {}) {
      # buildNpmPackage accepts env as a plain attrset merged into the
      # derivation; the above env field handles the most common case but
      # some nixpkgs versions require explicit passAsFile or inherit.
      # Keep both for compatibility.
    });
}
