# lib/npm-services.nix
#
# Factory for local npm-based service derivations (PRD-002 §9, Phase 1).
#
# Usage:
#   npmServices = import ./lib/npm-services.nix { inherit lib pkgs; };
#   managementApiPkg = npmServices.makeNpmService {
#     name    = "management-api";
#     src     = ./management-api;
#     entry   = "server.js";
#     npmDepsHash = "<prefetched>";
#   };
#
# Output layout (what buildNpmPackage produces):
#   $out/lib/node_modules/<name>/   — full package tree including node_modules
#   $out/bin/<name>                 — wrapper generated by postInstall below
#
# Operator: compute npmDepsHash for each service by running:
#   nix run nixpkgs#prefetch-npm-deps -- <service>/package-lock.json
# or:
#   nix-prefetch-url --type sha256 file://$(nix-build -E \
#     'with import <nixpkgs> {}; fetchNpmDeps { src = ./path; hash = ""; }')
#
# Placeholder behaviour: when `npmDepsHash = lib.fakeHash` is passed, the
# evaluation proceeds with a substituted placeholder SRI so every flake
# consumer (nix flake check, nix eval, nix build .#compose) stays green.
# `nix build .#runtime` surfaces the hash mismatch at realisation time with
# Nix's standard "expected vs got" message, plus a preFetch hint pointing at
# the resolver command.

{ lib, pkgs }:

let
  # Guard behaviour: throwing at evaluation time breaks every flake consumer
  # (nix flake check, nix build .#compose, nix eval, CI lint), not just the
  # operator who forgot to prefetch. Instead we detect the fakeHash and route
  # to a realisation-time failure so lazy evaluation consumers stay green.
  # When buildNpmPackage actually runs and fetches deps, the placeholder SRI
  # will mismatch and Nix will print both expected and got — same UX as any
  # other stale hash, with our preBuildPhase adding a pointed hint.
  fakeHashHint = name: ''
    echo "========================================" >&2
    echo "agentbox npm-service: ${name}" >&2
    echo "npmDepsHash is still lib.fakeHash. Compute the real hash:" >&2
    echo "  nix run nixpkgs#prefetch-npm-deps -- ${name}/package-lock.json" >&2
    echo "Then replace lib.fakeHash in lib/npm-services.nix." >&2
    echo "========================================" >&2
  '';

  # When fakeHash is passed, substitute a placeholder SRI so Nix can still
  # evaluate the derivation. The buildNpmPackage fetch step will fail with a
  # hash mismatch, and preBuildHook (injected below when fakeHash was used)
  # emits the operator-friendly pointer.
  resolvedHash = hash:
    if hash == lib.fakeHash
    then "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    else hash;

  isFakeHash = hash: hash == lib.fakeHash;

in

{
  # makeNpmService wraps pkgs.buildNpmPackage with the conventions required by
  # agentbox:
  #   - node_modules are baked in at build time (npmDepsHash)
  #   - a thin wrapper script is installed to $out/bin/<name> so supervisord
  #     can reference a single stable path instead of the JS entrypoint
  #   - checkPhase verifies the closure loads (catches broken imports early)
  #
  # Parameters:
  #   name              string   package name (also the bin wrapper name)
  #   src               path     path to directory containing package.json
  #   entry             string   JS entrypoint relative to the package root
  #                              e.g. "server.js" or "dist/mcp-server.js"
  #   npmDepsHash       string   sha256 from prefetch-npm-deps. `lib.fakeHash`
  #                              is accepted as a placeholder; evaluation is
  #                              lazy, so the failure surfaces at realisation
  #                              time (when buildNpmPackage fetches deps),
  #                              not at flake-check time.
  #   extraBuildInputs  list     extra nativeBuildInputs (e.g. nodeGyp, python3)
  #   extraEnv          attrs    additional environment variables set during build
  #   buildPhaseExtra   string   additional shell commands injected into buildPhase
  #                              (used for TypeScript compilation via tsc)
  #   skipLoadCheck     bool     when true, do not `require()`/`import()` the
  #                              entrypoint in checkPhase because module load
  #                              has side effects (e.g. starts a server)
  makeNpmService = {
    name,
    src,
    entry,
    npmDepsHash,
    extraBuildInputs ? [],
    extraEnv        ? {},
    buildPhaseExtra ? "",
    skipLoadCheck   ? false,
  }:
    let
      effectiveHash = resolvedHash npmDepsHash;
      needsHint     = isFakeHash npmDepsHash;
    in
    pkgs.buildNpmPackage ({
      pname   = name;
      version = "0.0.0";  # version is read from package.json at runtime; not
                           # semantically significant for image derivation tracking
      inherit src;

      # Pin to Node 22 to match the rest of the image (single Node major).
      nodejs = pkgs.nodejs_22;

      npmDepsHash = effectiveHash;

      # Fakehash hint: emits an operator-friendly message if the build is
      # attempted without prefetching. Harmless on real hashes (no-op).
      preFetch = lib.optionalString needsHint (fakeHashHint name);

      # Do not run npm test automatically — each service has its own test
      # runner; checkPhase below does a lightweight import check instead.
      doCheck = true;

      # Extra native build inputs (e.g. node-gyp + python for native addons).
      nativeBuildInputs = [ pkgs.nodejs_22 ] ++ extraBuildInputs;

      # Upstream @opentelemetry/* packages ship with overlapping peer-version
      # constraints that npm 7+ strict resolver rejects. The npmDepsHash
      # prefetch has already validated the resolved tree in a separate pass
      # (`nix run nixpkgs#prefetch-npm-deps -- <service>/package-lock.json`),
      # so telling npm to skip its re-validation here is safe and matches
      # nix's own error hint: "Set npmFlags = [ \"--legacy-peer-deps\" ]".
      npmFlags = [ "--legacy-peer-deps" ];

      # Extra env vars injected into the build sandbox.
      # Callers pass a string-to-string attrset; we emit KEY=VALUE pairs.
      env = extraEnv;

      # buildPhase: run any pre-packaging step (e.g. TypeScript compilation),
      # then skip 'npm run build' (not all packages define it).
      buildPhase = ''
        runHook preBuild
        ${buildPhaseExtra}
        runHook postBuild
      '';

      # checkPhase: confirm the entrypoint can be required without crashing.
      # This catches broken peer dependencies before the image layer is frozen.
      checkPhase = ''
        runHook preCheck
        if [ "${if skipLoadCheck then "1" else "0"}" = "1" ]; then
          test -f "./${entry}" \
            || { echo "[check] ${name}: missing entry ./${entry}" >&2; exit 1; }
        else
          node -e "require('./${entry}')" 2>/dev/null \
            || node --input-type=module <<<"import './${entry}'" 2>/dev/null \
            || echo "[check] ${name}: import check skipped (ESM-only or side-effect-free module)"
        fi
        runHook postCheck
      '';

      # postInstall: buildNpmPackage places the package at
      #   $out/lib/node_modules/<package.json "name">/
      # which is NOT always equal to the Nix-side `name` we pass. Example:
      # `management-api` here ↔ `agentic-flow-management-api` in package.json.
      # We resolve the real name at build time, then:
      #   - stamp it into the $out/bin wrapper as an absolute store path
      #     (unquoted heredoc expansion so the path is resolved at build
      #     time, NOT at container runtime where $out is unavailable),
      #   - point $out/package at that resolved directory so appRoot can
      #     copy the full tree including node_modules into /opt/agentbox/<name>.
      postInstall = ''
        # Read the package.json "name" field. [].join() stands in for an
        # empty-string fallback — we cannot write a literal JS empty string
        # here without tripping Nix's indented-string lexer or the outer
        # node -e shell quoting. Same pattern used in lib/npm-cli.nix.
        actual_name=$(${pkgs.nodejs_22}/bin/node -e "process.stdout.write(require('./package.json').name || [].join());")
        if [ -z "$actual_name" ]; then
          echo "ERROR: package.json has no 'name' for Nix pname=${name}" >&2
          exit 1
        fi
        pkg_dir="$out/lib/node_modules/$actual_name"
        if [ ! -d "$pkg_dir" ]; then
          echo "ERROR: expected $pkg_dir (from package.json name='$actual_name') but buildNpmPackage did not create it" >&2
          ls -la "$out/lib/node_modules/" || true
          exit 1
        fi

        # Wrapper script for supervisord command= lines. Unquoted heredoc so
        # $pkg_dir expands at build time; runtime variables stay escaped.
        mkdir -p "$out/bin"
        cat > "$out/bin/${name}" <<WRAPPER
        #!/usr/bin/env sh
        exec node "$pkg_dir/${entry}" "\$@"
        WRAPPER
        chmod +x "$out/bin/${name}"

        # Also expose the resolved package root as $out/package for appRoot
        # to cp into /opt/agentbox/<name> (includes node_modules).
        ln -s "$pkg_dir" "$out/package"
      '';

      meta = {
        description = "Agentbox npm service: ${name}";
        mainProgram  = name;
      };
    } // lib.optionalAttrs (extraEnv != {}) {
      # buildNpmPackage accepts env as a plain attrset merged into the
      # derivation; the above env field handles the most common case but
      # some nixpkgs versions require explicit passAsFile or inherit.
      # Keep both for compatibility.
    });
}
