#!/usr/bin/env bash
# reconcile-agents.sh — make the Claude Code agent roots a deterministic reflection
# of the curated registered-agents manifest, sourced from the baked
# /opt/agentbox/agents tree.
#
# The agent equivalent of reconcile-skills.sh, and written for the same reason.
# ~/.claude/agents and $WORKSPACE/.claude/agents were never governed by anything:
# `ruflo init` (@claude-flow/cli) and `aqe init --auto` each dump their template
# sets there, ~/.claude is a host mount so the dumps survive every rebuild, and
# nothing removed or refreshed them. The result audited 2026-09-16 was 97 unique
# agents across two scopes (~6,540 prompt tokens every turn), 74 of them present
# in BOTH scopes with 37 byte-divergent — and because the project scope shadows
# the user scope, the truncated copy silently won. See ADR-2092.
#
# Three things happen here:
#   1. Every registered agent is linked from /opt/agentbox/agents/<name>.md into
#      the primary root (single source of truth, baked from source, so a rebuild
#      always yields the current agent and nothing goes stale).
#   2. Vendor-dumped agents are retired to a recoverable .superseded/ sidecar.
#      NOT deleted — same convention as project-skill-roots.mjs.
#   3. The secondary roots are collapsed entirely, so the visible agent set no
#      longer depends on which directory the session was launched from.
#
# An unregistered agent is treated as vendor-dumped when it sits in a
# SUBDIRECTORY of an agent root (every vendor template set is filed under
# category dirs: core/, consensus/, github/, flow-nexus/, sparc/, v3/, …) or when
# its body carries a vendor marker. Hand-written agents placed flat at the root
# with no marker are LEFT ALONE and reported — the reconciler never silently
# retires something a human wrote.
#
# Idempotent and FAIL-OPEN: it never exits non-zero in a way that could block boot.
#
# Usage: reconcile-agents.sh [--dry-run]
set -uo pipefail

AGENTS_TREE="${AGENTS_TREE:-/opt/agentbox/agents}"
PRIMARY_ROOT="${CLAUDE_AGENTS_DIR:-$HOME/.claude/agents}"
# Colon-separated roots that are collapsed wholesale (everything retired).
SECONDARY_ROOTS="${AGENT_ROOT_TARGETS:-}"
MANIFEST="${REGISTERED_AGENTS_MANIFEST:-$AGENTS_TREE/registered-agents.txt}"
# Bodies matching any of these were generated by claude-flow / ruv-swarm / aqe.
VENDOR_MARKERS='npx claude-flow|ruv-swarm|flow-nexus|mcp__claude-flow__swarm_init|echo "(🐝|🚀|💻|🧠|📊|🔍|✅)'

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

log() { echo "[reconcile-agents] $*"; }

if [ ! -f "$MANIFEST" ]; then
  log "manifest not found at $MANIFEST — skipping (no-op)"
  exit 0
fi
mkdir -p "$PRIMARY_ROOT" 2>/dev/null || true

# ── read the manifest into a lookup ────────────────────────────────────────
REGISTERED=""
registered=0
while IFS= read -r raw; do
  name="${raw%%#*}"; name="$(printf '%s' "$name" | tr -d '[:space:]')"
  [ -z "$name" ] && continue
  REGISTERED="$REGISTERED $name"
  registered=$((registered + 1))
done < "$MANIFEST"

is_registered() {
  case " $REGISTERED " in *" $1 "*) return 0 ;; *) return 1 ;; esac
}

# ── retire one path into the root's .superseded/ sidecar ───────────────────
# Recoverable, not destructive: the operator can restore from .superseded/.
retire() {
  local root="$1" path="$2" why="$3"
  local rel="${path#"$root"/}"
  local dest="$root/.superseded/$rel"
  if [ "$DRY_RUN" -eq 1 ]; then log "DRY retire ($why): $rel"; return 0; fi
  mkdir -p "$(dirname "$dest")" 2>/dev/null || true
  if mv -f "$path" "$dest" 2>/dev/null; then
    log "retired ($why): $rel"
    return 0
  fi
  # A root-owned legacy file under an unprivileged run: report, do not thrash.
  log "ERROR cannot retire $rel (removal failed — likely root-owned; the boot reconciler runs privileged and will fix it)"
  return 1
}

# ── delete directories left empty by retirement, never the sidecar ─────────
# Repeated passes so a nested vendor tree (specialized/mobile/…) collapses fully.
prune_empty_dirs() {
  local root="$1" pass
  [ -d "$root" ] || return 0
  [ "$DRY_RUN" -eq 1 ] && return 0
  for pass in 1 2 3 4 5; do
    find "$root" -mindepth 1 -type d -empty \
      ! -name .superseded ! -path "$root/.superseded/*" \
      -exec rmdir {} + 2>/dev/null || true
  done
}

# ── phase 1: link the registered set into the primary root ─────────────────
linked=0 fixed=0 ok=0 missing=0
for name in $REGISTERED; do
  src="$AGENTS_TREE/$name.md"
  dst="$PRIMARY_ROOT/$name.md"

  if [ ! -f "$src" ]; then
    log "WARN registered '$name' has no $src — not baked; leaving any existing registration untouched"
    missing=$((missing + 1))
    continue
  fi

  if [ -L "$dst" ] && [ "$(readlink -f "$dst" 2>/dev/null)" = "$(readlink -f "$src" 2>/dev/null)" ]; then
    ok=$((ok + 1))
    continue
  fi

  if [ -e "$dst" ] || [ -L "$dst" ]; then
    if [ "$DRY_RUN" -eq 1 ]; then log "DRY relink: $dst -> $src"; continue; fi
    rm -f "$dst" 2>/dev/null || true
    if [ -e "$dst" ] || [ -L "$dst" ]; then
      log "ERROR cannot replace $name (removal failed — likely root-owned)"
      continue
    fi
    fixed=$((fixed + 1)); action="relinked"
  else
    linked=$((linked + 1)); action="linked new"
  fi
  [ "$DRY_RUN" -eq 1 ] && { log "DRY $action: $name"; continue; }
  ln -sfn "$src" "$dst" 2>/dev/null && log "$action: $name" || log "ERROR linking $name"
done

# ── phase 2: retire vendor dumps from the primary root ─────────────────────
retired=0 kept=0
if [ -d "$PRIMARY_ROOT" ]; then
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    base="$(basename "$f" .md)"
    rel="${f#"$PRIMARY_ROOT"/}"
    # Depth first, and BEFORE the registered check: a vendor copy filed under a
    # category dir is retired even when its basename matches a registered agent.
    # Skipping those on name alone leaves e.g. v3/adr-architect.md next to our
    # own adr-architect.md — two agents with one name, and which one the Agent
    # tool serves depends on scan order. That is the bug this script exists to
    # remove, so it must not reintroduce it.
    if [ "$rel" != "${rel%/*}" ]; then
      retire "$PRIMARY_ROOT" "$f" "vendor category dir" && retired=$((retired + 1))
      continue
    fi
    # Flat file with a registered name: this is our own symlink from phase 1.
    is_registered "$base" && continue
    if grep -qE "$VENDOR_MARKERS" "$f" 2>/dev/null; then
      retire "$PRIMARY_ROOT" "$f" "vendor marker" && retired=$((retired + 1))
    else
      log "KEPT unmanaged (hand-written, no vendor marker): $rel"
      kept=$((kept + 1))
    fi
  done <<EOF
$(find "$PRIMARY_ROOT" -path "$PRIMARY_ROOT/.superseded" -prune -o -type f -name '*.md' -print 2>/dev/null)
EOF
  # Category dirs left empty by the retirements above are vendor scaffolding too.
  # NOTE: -delete implies -depth, which silently nullifies -prune — exclude the
  # sidecar by path test instead, or the retired copies get deleted with it.
  prune_empty_dirs "$PRIMARY_ROOT"
fi

# ── phase 3: collapse the secondary roots ──────────────────────────────────
# These exist only because `ruflo init` was run from a nested CWD. The Agent tool
# reads the nearest root, so a stale duplicate here SHADOWS the primary one —
# which is how 37 divergent agents came to be served from the truncated copy.
collapsed=0
if [ -n "$SECONDARY_ROOTS" ]; then
  IFS=':' read -r -a _roots <<< "$SECONDARY_ROOTS"
  for root in "${_roots[@]}"; do
    [ -n "$root" ] && [ -d "$root" ] || continue
    [ "$(readlink -f "$root" 2>/dev/null)" = "$(readlink -f "$PRIMARY_ROOT" 2>/dev/null)" ] && continue
    while IFS= read -r f; do
      [ -n "$f" ] || continue
      retire "$root" "$f" "secondary root" && collapsed=$((collapsed + 1))
    done <<EOF
$(find "$root" -path "$root/.superseded" -prune -o -type f -name '*.md' -print 2>/dev/null)
EOF
    prune_empty_dirs "$root"
  done
fi

drylabel=""; [ "$DRY_RUN" -eq 1 ] && drylabel=" (dry-run)"
log "done: $registered registered | new=$linked relinked=$fixed already-ok=$ok not-baked=$missing | retired=$retired kept-unmanaged=$kept collapsed-secondary=$collapsed${drylabel}"
exit 0
