//! Project the instruction tiers from the agentbox repo (ADR-2118).
//!
//! Two tiers sit above every repository and so cannot live in one: the global
//! tier (`~/.claude/CLAUDE.md`) and the workspace tier (`~/workspace/AGENTS.md`).
//! They used to be hand-kept files on a host bind and a Docker volume, with no
//! history and no review. They are now composed from two layers in the repo,
//! mounted read-only at `/etc/agentbox/instructions`:
//!
//! * `<tier>.md` — tracked, public, tool-neutral product rules;
//! * `local/<tier>.md` — gitignored operator/estate layer (addresses, private
//!   repository names, personal working style). Never baked into the image.
//!
//! Tiers: `global` → `~/.claude/CLAUDE.md`; `workspace` → `~/workspace/AGENTS.md`
//! (tool-neutral, also appended to Codex's `AGENTS.md` by the entrypoint);
//! `workspace.claude` → `~/workspace/CLAUDE.md`, Claude-only notes into whose
//! `@AGENTS.md` line the composed workspace tier is embedded (ADR-2111: an
//! import above the project root would be skipped as an external include).
//!
//! The repo is authoritative: every boot rewrites the outputs, so a live edit
//! does not survive. Each output starts with a marker naming its sources.

use std::path::{Path, PathBuf};

/// First line of every generated file; also how a generated file is recognised.
pub fn header(tier: &str) -> String {
    format!(
        "<!-- GENERATED by `agentbox-manifest instructions-project` from agentbox \
         config/instructions/{tier}.md + config/instructions/local/{tier}.md. \
         Edit those; this file is overwritten every boot. -->"
    )
}

/// Pure: the output text for `tier` from its tracked and local layers, or
/// `None` when both are absent (nothing to own — leave the target alone).
pub fn compose(tier: &str, tracked: Option<&str>, local: Option<&str>) -> Option<String> {
    let parts: Vec<&str> = [tracked, local]
        .into_iter()
        .flatten()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect();
    if tracked.is_none() && local.is_none() {
        return None;
    }
    Some(format!("{}\n\n{}\n", header(tier), parts.join("\n\n")))
}

fn read(p: &Path) -> Option<String> {
    std::fs::read_to_string(p).ok()
}

/// Layer paths for `tier` under `layers`.
pub fn layer_paths(layers: &Path, tier: &str) -> (PathBuf, PathBuf) {
    (
        layers.join(format!("{tier}.md")),
        layers.join("local").join(format!("{tier}.md")),
    )
}

/// The composed text for `tier` read from disk.
pub fn composed(layers: &Path, tier: &str) -> Option<String> {
    let (t, l) = layer_paths(layers, tier);
    compose(tier, read(&t).as_deref(), read(&l).as_deref())
}

/// Outcome for one target.
#[derive(Debug, PartialEq, Eq)]
pub enum Outcome {
    Unchanged,
    Written,
    Drift,
    NoLayers,
}

/// Compose `tier` and bring `target` into line. `check` reports drift instead
/// of writing. Writes are atomic (temp file + rename in the target directory).
/// With `embed`, that text replaces the tier's `@AGENTS.md` line.
pub fn project(
    layers: &Path,
    tier: &str,
    target: &Path,
    check: bool,
    embed: Option<&str>,
) -> Result<Outcome, String> {
    let Some(mut next) = composed(layers, tier) else {
        return Ok(Outcome::NoLayers);
    };
    if let Some(src) = embed {
        next = crate::agents_md::embed(&next, src);
    }
    if read(target).as_deref() == Some(next.as_str()) {
        return Ok(Outcome::Unchanged);
    }
    if check {
        return Ok(Outcome::Drift);
    }
    if let Some(dir) = target.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    let tmp = target.with_extension("md.instructions.tmp");
    std::fs::write(&tmp, &next).map_err(|e| format!("{}: {e}", tmp.display()))?;
    std::fs::rename(&tmp, target).map_err(|e| format!("{}: {e}", target.display()))?;
    Ok(Outcome::Written)
}

/// CLI entry. Fail-open on write errors (boot must not break over an
/// instruction file); with `check`, an error when any target has drifted.
///
/// `global_out` is `None` where `~/.claude` is still the host's own directory
/// (a legacy whole-directory bind): the host keeps its global file, so it is
/// never overwritten from the repo.
pub fn run(
    layers: &Path,
    global_out: Option<&Path>,
    workspace_out: &Path,
    workspace_claude_out: &Path,
    check: bool,
) -> Result<(), String> {
    let mut drift = false;
    let ws = composed(layers, "workspace");
    let targets = [
        ("global", global_out, None),
        ("workspace", Some(workspace_out), None),
        ("workspace.claude", Some(workspace_claude_out), ws.as_deref()),
    ];
    for (tier, target, embed) in targets {
        let Some(target) = target else {
            println!("  [instructions] {tier} skipped: ~/.claude is the host's directory");
            continue;
        };
        match project(layers, tier, target, check, embed) {
            Ok(Outcome::Written) => println!("  [instructions] projected {tier} → {}", target.display()),
            Ok(Outcome::Drift) => {
                println!("  [instructions] DRIFT: {} differs from its {tier} layers", target.display());
                drift = true;
            }
            Ok(Outcome::NoLayers) => eprintln!("  [instructions] no {tier} layers under {} — {} left as is", layers.display(), target.display()),
            Ok(Outcome::Unchanged) => {}
            Err(e) => {
                eprintln!("  [instructions] {tier}: {e}");
                drift |= check;
            }
        }
    }
    if drift {
        return Err("instruction tiers have drifted from their layers".into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("instr-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(d.join("local")).unwrap();
        d
    }

    #[test]
    fn composes_tracked_then_local_under_a_header() {
        let out = compose("workspace", Some("# Env\nfact\n"), Some("## Estate\nip\n")).unwrap();
        assert!(out.starts_with("<!-- GENERATED"));
        assert!(out.find("fact").unwrap() < out.find("## Estate").unwrap());
        assert!(out.ends_with("ip\n"));
    }

    #[test]
    fn a_missing_local_layer_is_fine_and_both_missing_owns_nothing() {
        assert!(compose("global", Some("x"), None).unwrap().ends_with("\nx\n"));
        assert!(compose("global", None, Some("y")).unwrap().ends_with("\ny\n"));
        assert_eq!(compose("global", None, None), None);
    }

    #[test]
    fn projects_idempotently_and_overwrites_live_edits() {
        let d = scratch("proj");
        std::fs::write(d.join("workspace.md"), "# Env\n").unwrap();
        std::fs::write(d.join("local/workspace.md"), "estate\n").unwrap();
        let out = d.join("out/AGENTS.md");
        assert_eq!(project(&d, "workspace", &out, false, None).unwrap(), Outcome::Written);
        assert_eq!(project(&d, "workspace", &out, false, None).unwrap(), Outcome::Unchanged);
        std::fs::write(&out, "hand edit\n").unwrap();
        assert_eq!(project(&d, "workspace", &out, true, None).unwrap(), Outcome::Drift);
        assert_eq!(project(&d, "workspace", &out, false, None).unwrap(), Outcome::Written);
        assert!(std::fs::read_to_string(&out).unwrap().contains("estate"));
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn claude_notes_embed_the_workspace_tier_and_check_sees_no_drift() {
        let d = scratch("embed");
        std::fs::write(d.join("workspace.md"), "# Env\nfact one\n").unwrap();
        std::fs::write(d.join("workspace.claude.md"), "# Claude notes\n\n@AGENTS.md\n\n## Browser\nskill\n").unwrap();
        let (g, w, c) = (d.join("g/CLAUDE.md"), d.join("w/AGENTS.md"), d.join("w/CLAUDE.md"));
        run(&d, Some(&g), &w, &c, false).unwrap();
        let claude = std::fs::read_to_string(&c).unwrap();
        assert!(!claude.contains("\n@AGENTS.md\n"));
        assert!(claude.find("fact one").unwrap() < claude.find("## Browser").unwrap());
        assert!(!g.exists(), "global has no layers here");
        assert!(run(&d, Some(&g), &w, &c, true).is_ok());
        std::fs::write(d.join("local/workspace.md"), "estate\n").unwrap();
        assert!(run(&d, Some(&g), &w, &c, true).is_err(), "a layer edit is drift until projected");
        run(&d, Some(&g), &w, &c, false).unwrap();
        assert!(std::fs::read_to_string(&c).unwrap().contains("estate"));
        std::fs::write(d.join("global.md"), "# G\n").unwrap();
        run(&d, None, &w, &c, false).unwrap();
        assert!(!g.exists(), "a skipped global tier is never written");
        std::fs::remove_dir_all(&d).ok();
    }

    #[test]
    fn no_layers_leaves_the_target_untouched() {
        let d = scratch("none");
        let out = d.join("CLAUDE.md");
        std::fs::write(&out, "host-owned\n").unwrap();
        assert_eq!(project(&d, "global", &out, false, None).unwrap(), Outcome::NoLayers);
        assert_eq!(std::fs::read_to_string(&out).unwrap(), "host-owned\n");
        std::fs::remove_dir_all(&d).ok();
    }
}
