//! Profile-tree provisioning — the port of `scripts/provision-agent-stacks.py`.
//!
//! Runs as root at boot stage `[4/8]`. It is pure config projection: a
//! `workspace/profiles/<name>/` tree per stack with an `.env`, a `README.md`,
//! shared-mount symlinks, and (for Claude-hosted profiles) a
//! `.claude/settings.json` carrying the self-learning hook wiring.
//!
//! `STACKS` is kept as a JSON literal rather than Rust structs for one reason:
//! it is emitted verbatim into `stack-manifest.json`, so its key order is part
//! of the byte-for-byte contract, and a literal makes that order reviewable
//! against the Python at a glance.

use std::path::Path;

use serde_json::{Map, Value};

use crate::stacks_env::{as_string, Env, Gates};
use crate::{jsonio, tomlval};

const STACKS_JSON: &str = include_str!("stacks.json");

/// Claude Code hook wiring for the claude-flow self-learning loop.
///
/// Every hook delegates to the baked stdin→CLI adapter, which routes through
/// the mandated ruvector-postgres backend (ADR-015). `|| true` keeps a missing
/// binary from ever breaking a session, and `session-end` binds to `SessionEnd`
/// only (never `Stop`) so per-session consolidation does not fire every turn.
fn learning_hooks(env: &Env, gates: &Gates) -> Value {
    let cmd = |action: &str, timeout: i64| {
        serde_json::json!({
            "type": "command",
            "command": format!("node {} {action} || true", env.hook_adapter),
            "timeout": timeout,
        })
    };

    let mut session_end = vec![serde_json::json!({ "hooks": [cmd("session-end", 10000)] })];
    if gates.mobile_bridge {
        session_end.push(serde_json::json!({ "hooks": [{
            "type": "command",
            "command": format!("python3 {} || true", env.nostr_summary_hook),
            "timeout": 200000,
        }] }));
    }
    if gates.ontology_monitor {
        session_end.push(serde_json::json!({ "hooks": [{
            "type": "command",
            "command": format!("node {} || true", env.ontology_monitor_hook),
            "timeout": 200000,
        }] }));
    }

    serde_json::json!({
        "PreToolUse": [
            {"matcher": "Bash", "hooks": [cmd("pre-command", 5000)]},
            {"matcher": "Write|Edit|MultiEdit", "hooks": [cmd("pre-edit", 5000)]},
        ],
        "PostToolUse": [
            {"matcher": "Write|Edit|MultiEdit", "hooks": [cmd("post-edit", 10000)]},
            {"matcher": "Bash", "hooks": [cmd("post-command", 5000)]},
        ],
        "UserPromptSubmit": [{"hooks": [cmd("route", 12000)]}],
        "SessionStart": [{"hooks": [cmd("session-restore", 15000)]}],
        "SessionEnd": session_end,
    })
}

fn write_text(path: &Path, content: &str) -> Result<(), String> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    std::fs::write(path, content).map_err(|e| format!("{}: {e}", path.display()))
}

/// Replace `target` with a symlink to `source`, clearing whatever is there.
///
/// A broken symlink reports `exists() == False` in Python but is caught by the
/// `or target.is_symlink()` arm; `symlink_metadata` is the Rust equivalent that
/// does not follow the link.
fn symlink_replace(target: &Path, source: &Path) -> Result<(), String> {
    if let Some(dir) = target.parent() {
        std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    }
    if let Ok(md) = std::fs::symlink_metadata(target) {
        let removed = if md.file_type().is_symlink() || md.is_file() {
            std::fs::remove_file(target)
        } else {
            std::fs::remove_dir_all(target)
        };
        removed.map_err(|e| format!("{}: {e}", target.display()))?;
    }
    std::os::unix::fs::symlink(source, target).map_err(|e| format!("{}: {e}", target.display()))
}

fn str_list(v: &Value) -> Vec<String> {
    v.as_array()
        .map(|a| a.iter().map(|x| as_string(Some(x))).collect())
        .unwrap_or_default()
}

fn build_profile(name: &str, config: &Value, env: &Env, gates: &Gates) -> Result<(), String> {
    let root = env.workspace.join("profiles").join(name);
    let claude_dir = root.join(".claude");

    let mut env_lines = vec![
        "# Generated by Agentbox".to_string(),
        format!("AGENT_STACK={name}"),
    ];
    for key in str_list(&config["env"]) {
        env_lines.push(format!("{key}={}", std::env::var(&key).unwrap_or_default()));
    }

    symlink_replace(&root.join("projects"), &env.shared_projects_root)?;
    symlink_replace(&root.join("workspace"), &env.workspace)?;
    write_text(&root.join(".env"), &(env_lines.join("\n") + "\n"))?;

    for extra in config.get("extra_dirs").map(str_list).unwrap_or_default() {
        let d = root.join(extra);
        std::fs::create_dir_all(&d).map_err(|e| format!("{}: {e}", d.display()))?;
    }

    let skills = str_list(&config["skills"]);
    let tools = str_list(&config["tools"]);
    let layout = env
        .workspace
        .join(".config/zellij/layouts")
        .join(format!("{name}.kdl"));
    let skill_index = env.skills_tree.join("SKILL-DIRECTORY.md");

    let mut readme = vec![
        format!("# {name}"),
        String::new(),
        "Provisioned stack profile for Agentbox.".into(),
        String::new(),
        format!(
            "Shared external projects mount: {}",
            env.shared_projects_root.display()
        ),
        format!("Shared workspace mount: {}", env.workspace.display()),
        format!("Shared skills tree: {}", env.skills_tree.display()),
        format!("Zellij layout: {}", layout.display()),
        format!("Agent URN: urn:agentbox:agent:{name}"),
        String::new(),
        "Tools:".into(),
    ];
    readme.extend(tools.iter().map(|t| format!("- {t}")));
    readme.push(String::new());
    readme.push("Recommended skills:".into());
    readme.extend(skills.iter().map(|s| format!("- {s}")));
    readme.push(String::new());
    readme.push(format!(
        "Progressive disclosure index: {}",
        skill_index.display()
    ));
    readme.push(String::new());
    write_text(&root.join("README.md"), &readme.join("\n"))?;

    // Profiles hosting a non-Claude agent manage their own config format.
    if config
        .get("no_claude_settings")
        .and_then(Value::as_bool)
        .unwrap_or(false)
    {
        return Ok(());
    }

    let mut settings_env = Map::new();
    settings_env.insert(
        "CLAUDE_FLOW_HOOKS_ENABLED".into(),
        Value::String("true".into()),
    );
    settings_env.insert(
        "CLAUDE_FLOW_V3_ENABLED".into(),
        Value::String("true".into()),
    );
    settings_env.insert(
        "TRANSFORMERS_CACHE".into(),
        Value::String(env.hf_cache.clone()),
    );
    settings_env.insert("HF_HOME".into(), Value::String(env.hf_cache.clone()));
    if gates.mobile_bridge && !gates.summary_model.is_empty() {
        settings_env.insert(
            "AGENTBOX_ZAI_MODEL".into(),
            Value::String(gates.summary_model.clone()),
        );
    }
    if gates.ontology_monitor {
        settings_env.insert(
            "AGENTBOX_ONTOLOGY_MONITOR".into(),
            Value::String("1".into()),
        );
        settings_env.insert(
            "AGENTBOX_ONTOLOGY_MONITOR_MODE".into(),
            Value::String(gates.ontology_monitor_mode.clone()),
        );
    }
    if !gates.zai_reasoning_effort.is_empty() {
        settings_env.insert(
            "AGENTBOX_ZAI_REASONING_EFFORT".into(),
            Value::String(gates.zai_reasoning_effort.clone()),
        );
    }

    let settings = serde_json::json!({
        "stack": name,
        "skillsDirectory": env.skills_tree.to_string_lossy(),
        "progressiveDisclosureIndex": skill_index.to_string_lossy(),
        "sharedProjectsRoot": env.shared_projects_root.to_string_lossy(),
        "zellijLayout": layout.to_string_lossy(),
        "recommendedSkills": skills,
        "tooling": tools,
        "agentUrn": format!("urn:agentbox:agent:{name}"),
        "didTemplate": "did:nostr:{AGENTBOX_PUBKEY_HEX}",
        "env": Value::Object(settings_env),
        "hooks": learning_hooks(env, gates),
    });

    symlink_replace(&claude_dir.join("skills"), &env.skills_tree)?;
    write_text(
        &claude_dir.join("settings.json"),
        &(jsonio::dumps(&settings) + "\n"),
    )
}

pub fn provision() -> Result<(), String> {
    let env = Env::from_process();
    let text = std::fs::read_to_string(&env.agentbox_config)
        .map_err(|e| format!("{}: {e}", env.agentbox_config.display()))?;
    let cfg =
        tomlval::parse(&text).map_err(|e| format!("{}: {e}", env.agentbox_config.display()))?;
    let gates = Gates::from_manifest(&cfg);

    let stacks: Value = serde_json::from_str(STACKS_JSON).expect("baked STACKS is valid JSON");
    let stack_map = stacks.as_object().expect("STACKS is an object");

    for (name, stack) in stack_map {
        build_profile(name, stack, &env, &gates)?;
    }

    let mut manifest = Map::new();
    manifest.insert(
        "generated_from".into(),
        Value::String(env.agentbox_config.to_string_lossy().into_owned()),
    );
    manifest.insert(
        "skills_tree".into(),
        Value::String(env.skills_tree.to_string_lossy().into_owned()),
    );
    manifest.insert(
        "shared_projects_root".into(),
        Value::String(env.shared_projects_root.to_string_lossy().into_owned()),
    );
    manifest.insert("stacks".into(), stacks.clone());
    manifest.insert(
        "toolchains".into(),
        cfg.get("toolchains")
            .cloned()
            .unwrap_or_else(|| Value::Object(Map::new())),
    );

    write_text(
        &env.workspace.join(".agentbox/stack-manifest.json"),
        &(jsonio::dumps(&Value::Object(manifest)) + "\n"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn test_env(root: &Path) -> Env {
        Env {
            workspace: root.join("ws"),
            skills_tree: "/opt/agentbox/skills".into(),
            agentbox_config: root.join("agentbox.toml"),
            shared_projects_root: "/projects".into(),
            hook_adapter: "/opt/agentbox/config/hooks/claude-flow-hook-adapter.cjs".into(),
            nostr_summary_hook: "/opt/agentbox/config/hooks/nostr-session-summary.py".into(),
            ontology_monitor_hook: "/opt/agentbox/config/hooks/ontology-monitor.cjs".into(),
            hf_cache: "/home/devuser/.cache/huggingface".into(),
        }
    }

    fn no_gates() -> Gates {
        Gates {
            mobile_bridge: false,
            summary_model: String::new(),
            zai_reasoning_effort: String::new(),
            ontology_monitor: false,
            ontology_monitor_mode: "dryrun".into(),
        }
    }

    #[test]
    fn baked_stacks_parse_and_carry_every_profile() {
        let stacks: Value = serde_json::from_str(STACKS_JSON).unwrap();
        let names: Vec<&String> = stacks.as_object().unwrap().keys().collect();
        assert_eq!(
            names,
            vec![
                "claude-core",
                "ruflo-orchestrator",
                "qe-fleet",
                "nagual-qe",
                "rust-builder",
                "docs-latex",
                "zai",
                "openrouter",
                "antigravity",
                "deepseek",
                "perplexity",
                "gemma",
                "codex",
            ]
        );
    }

    #[test]
    fn base_hooks_have_no_session_end_extras() {
        let tmp = std::env::temp_dir();
        let h = learning_hooks(&test_env(&tmp), &no_gates());
        assert_eq!(h["SessionEnd"].as_array().unwrap().len(), 1);
        assert!(h["PreToolUse"][0]["hooks"][0]["command"]
            .as_str()
            .unwrap()
            .ends_with("pre-command || true"));
    }

    #[test]
    fn mobile_bridge_and_monitor_append_session_end_hooks_in_order() {
        let tmp = std::env::temp_dir();
        let gates = Gates {
            mobile_bridge: true,
            summary_model: "glm-5.3".into(),
            zai_reasoning_effort: String::new(),
            ontology_monitor: true,
            ontology_monitor_mode: "dryrun".into(),
        };
        let h = learning_hooks(&test_env(&tmp), &gates);
        let se = h["SessionEnd"].as_array().unwrap();
        assert_eq!(se.len(), 3);
        assert!(se[1]["hooks"][0]["command"]
            .as_str()
            .unwrap()
            .contains("nostr-session-summary.py"));
        assert!(se[2]["hooks"][0]["command"]
            .as_str()
            .unwrap()
            .contains("ontology-monitor.cjs"));
    }

    #[test]
    fn gates_default_to_off_with_dryrun_mode() {
        let cfg = tomlval::parse("[core]\nx = 1\n").unwrap();
        let g = Gates::from_manifest(&cfg);
        assert!(!g.mobile_bridge && !g.ontology_monitor);
        assert_eq!(g.ontology_monitor_mode, "dryrun");
        assert!(g.summary_model.is_empty());
    }

    #[test]
    fn summary_model_is_suppressed_when_the_bridge_is_off() {
        let cfg = tomlval::parse(
            "[sovereign_mesh.mobile_bridge]\nenabled = false\nsummary_model = \"glm-5.3\"\n",
        )
        .unwrap();
        assert!(Gates::from_manifest(&cfg).summary_model.is_empty());
    }

    #[test]
    fn no_claude_settings_profiles_skip_the_settings_file() {
        let tmp = tempdir();
        let env = test_env(&tmp);
        let stacks: Value = serde_json::from_str(STACKS_JSON).unwrap();
        build_profile("perplexity", &stacks["perplexity"], &env, &no_gates()).unwrap();
        assert!(env.workspace.join("profiles/perplexity/README.md").exists());
        assert!(!env
            .workspace
            .join("profiles/perplexity/.claude/settings.json")
            .exists());
        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn claude_profiles_write_settings_with_a_trailing_newline() {
        let tmp = tempdir();
        let env = test_env(&tmp);
        let stacks: Value = serde_json::from_str(STACKS_JSON).unwrap();
        build_profile("claude-core", &stacks["claude-core"], &env, &no_gates()).unwrap();
        let p = env
            .workspace
            .join("profiles/claude-core/.claude/settings.json");
        let text = std::fs::read_to_string(&p).unwrap();
        assert!(text.ends_with("}\n"));
        let v: Value = serde_json::from_str(&text).unwrap();
        assert_eq!(v["stack"], "claude-core");
        assert_eq!(v["agentUrn"], "urn:agentbox:agent:claude-core");
        let keys: Vec<&String> = v.as_object().unwrap().keys().collect();
        assert_eq!(keys[0], "stack");
        assert_eq!(keys[keys.len() - 1], "hooks");
        std::fs::remove_dir_all(&tmp).ok();
    }

    fn tempdir() -> PathBuf {
        let p = std::env::temp_dir().join(format!(
            "abm-stacks-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&p).unwrap();
        p
    }
}
